image:
  repository: machines/stash
  tag: enterprise

service:
  type: ClusterIP
  port: 8334

persistence:
  enabled: true
  storageClass: "local-path"
  size: 5Gi
  annotations:
    helm.sh/resource-policy: keep

nodeSelector: {}

envFrom: []

env: []
