apiVersion: v1
kind: Secret
metadata:
  name: prometheus-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: prometheus
type: kubernetes.io/service-account-token
