apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prometheus-custom-roles
    app.kubernetes.io/instance: prometheus-custom-roles
    app.kubernetes.io/managed-by: Helm
