apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-local-dns
  namespace: {{ .Release.Namespace }}
  labels:
    kubernetes.io/cluster-service: "true"
    app.kubernetes.io/name: nodelocal-dns
    app.kubernetes.io/instance: {{ .Release.Name }}
