apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../secrets/authelia
  - ../../secrets/filestash
  - ../../secrets/karakeep
  - ../../secrets/miniflux

  - ../base/authelia
  - ../base/filestash
  - ../base/karakeep
  - ../base/miniflux
  - ../base/trilium
  - ../base/gatus
