nodeSelector: {}

persistence:
  enabled: true
  size: 1Gi
  storageClassName: local-path
  annotations:
    helm.sh/resource-policy: keep

config:
  domain: ""
  autheliaUrl: ""

ldap:
  implementation: 'lldap'
  address: 'ldap://lldap.lldap.svc.cluster.local:3890'
  base_dn: ""
  user: ""
  password: ""

secrets:
  jwtSecret: ""
  sessionSecret: ""
  storageEncryptionKey: ""
  smtpAddress: ""
  smtpUsername: ""
  smtpPassword: ""
  smtpSender: ""
  oidcHmacSecret: ""
  oidcJwksKey: ""

oidcClients: []
