apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: n8n
type: Opaque
stringData:
    values.yaml: |
        service:
            nodePort: 30003
        persistence:
            enabled: true
            size: 100Gi
            storageClassName: nas
            accessModes:
                - ReadWriteOnce
        database:
            size: 5Gi
            storageClassName: local-path
        nodeSelector:
            kubernetes.io/hostname: kube-runner
        secrets:
            n8nEncryptionKey: 1a51d2d4bd4e4f9921c081a1a7ee3785
            runnersAuthToken: ac7dde222c3406335299077ebfc32c6e3e38a8feae3de01d35dc12b1559dbec1
        env:
            - name: N8N_HOST
              value: workflow.rmtt.tech
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: https
            - name: WEBHOOK_URL
              value: https://workflow.rmtt.tech/
            - name: N8N_EDITOR_BASE_URL
              value: https://workflow.rmtt.tech/
            - name: N8N_INSTANCE_OWNER_MANAGED_BY_ENV
              value: "true"
            - name: N8N_INSTANCE_OWNER_FIRST_NAME
              value: rmt
            - name: N8N_INSTANCE_OWNER_EMAIL
              value: iamrmttt@gmail.com
            - name: N8N_INSTANCE_OWNER_PASSWORD_HASH
              value: $2b$05$vB0yVFZCEgrDgYGmcxA.RetmJ5bu.Z64Ms5NAasXe2ZTI6xfK2cAe
