image: registry.k8s.io/dns/k8s-dns-node-cache:1.26.8

localDNS: 169.254.20.10
clusterDNS: 10.43.0.10
clusterDomain: cluster.local

resources:
  requests:
    cpu: 25m
    memory: 5Mi
  limits:
    cpu: 100m
    memory: 128Mi

cache:
  successTTL: 30
  denialTTL: 5

nodeSelector: {}
