apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: karakeep
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:MdDU19weVqIQ/1S0U5C4W6vGq5IouiLKnKi7KR3dQT+o0eXydG+VuOGcx84vCbiHIbnH/4NUglKJeviF5WF3gP5/rWUt6BFPo8mtlWwETV1VvhWwhXB9B9sTq1b6Zbv6m3IRn6llMB4eac6cPyFrO3zi4krPglPGKVu08jI5F0cgtpAlm1bvLbTNdVcoknkWuAWuF6+LLXXHZNe8i8qZ6ScUT77NfSq/hIop1hFf8quWnofl0MvfUIEY+7aMt6Uet+QN0cX4NZ0rmXxiPHLHehfQayIQH/3nTsKbGwHd8UvysVdvwYbuxUYqG3W6MBbHBNpwl+vlDyNp61mWaVbkGnOiPr6GCkc+uyz0eHcMM0w1hy700PF2aw1H6RM8hkQ1b3OLgq6CRlG1WB2JsEsoaFKb/7d2f6RH6FozHkjIM80t2sRcFfPi3KXvz0Dy4zXrXvH4eny9Z8fk3RVJw5y3SiUCM3mvMN2SObfUTJWRieJO17bq6lY8tgSSFB1fW91EgNyQNcZILblPbtYaafcJNNte5+ylFiIAAPF5yjxKBFrl0RI/aR7eWcaTl8ox0Bh2yuEQOI7BLsC+SJ8RR+iCiDkMflpH6c8BU1++d7cWmL02c4zTGVhCHkF9m4UF7QIt3hSYmgj1KiEC3vscTxfmqkVxy4VbPVDKReRa/nSaeFIcnUBwoypvHuGegncLJjEtbCBMkYO4arcR,iv:OKkjr8rJqYFFc7Xn2/RnxtHPD0Cn+ycP5yC/7fmeCbI=,tag:24jHjPFYjeHpPQSWACgxIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMTV6Vmh6Q05kTnRtV2FP
            cnBuSklaTm1WblpwNFhGTEkvUkhwTE9IZlVnClp1N2xoNmo4V2dxZkZvQ05pQ0Vr
            QStrOU5sUDBFMHVtVUNPNlNEWVRwM0kKLS0tIGwrNWhtbTI4c1pCaEttbDIwcXdE
            YVlKekYrajZ0SDVPTEF1RnVSSnFBU0kKs8CfIodIkWuFMS4bVtK6+loRRyKoDh+5
            ynIAiEFTGl3bsIjjo7+qw7fLGX+FwV2QMqOL6x1Xs+857iHbPDs+hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T04:25:19Z"
    mac: ENC[AES256_GCM,data:kOpdZ9fgPnwXf/+kGvgdbR6kr6vZ3rgSqG6lprgVB1AHXqtGQ6Syf1ptBLjHFqkihTLoTohr238I+oDAIm5ngsq5innIDp67Spd0PQURKe29pmXoS2WpmdK7R5byzijSAjFCu7lxAIzuh1v5BSfBWdDwxDdTK4Lj3vf8Ux43O5E=,iv:L46ES4YXp+qVOfHkEEhY62wmLHWzzkyS1oma427Y6Yg=,tag:z7+/HM9Ew7UV0F10xAs1uA==,type:str]
    pgp:
        - created_at: "2026-06-14T17:46:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA4w2YNyo4oB3m9sZlFSJor4uz7SPT5FVVAVTAwHAbNAsw
            mkKtrnvOjl8iEWu8WfcBQWzK0kTT2YUVdBY4lwjjOaNKNM7XEzEq4jqlG7MII4HD
            0lEBykkI1EEs8/wVLUo43OkoYJk4IJmFD3CsTDXLYKEq3hROzg1d/nXddPdHxMgH
            vd9/IgOqqlXpDGZ83t4JCwj2dbojoCl+LdwGIiyUXXf98Co=
            =8poF
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
