apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: karakeep
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ylW9n57G/blWQwTnSiIzO+SHPraL2lLezyXM7fRiCWIRKdOZ38XLv5npRCZeHgqFsnyMLPjmsYnmIFBdaOzCAYhZLTWpP1H900UeFqJ/civdgi+/tYtLGS+BibX534VbnSwBodwNq9c/CYomPYxgRn8tjbXER5PWGNOTdLevqkQWMeucoRL7k73sQRcW0OEvUGp3ngcXY3B6DEZW1y2+z4e1QcCpUr9PKECrwdgBBDxDEQVvhXSC3se++XEvzUbAG8e9ufxGFidGkpWCC/edCrUJuJZKEtOVgFluUrRyJ6bipDS5yY2uUjJDqGgny+qTJZ3Ap3y8dNMZEPCO6aFqEmMK6Yd6WaltpmHESvzkQXO3DLqOXSVl6kXEeuQQIJTI2Al69tRoWx6+OrU6eshoOHTzlNCwsGnVX1U2W5Lfr9DHk0rpIH9PgWn8EaCKM3ZipRtiHT6r3Dpv8H8OHNckbxify/3iCV42e5/riWAOWA7W74YSqJU1H5LLL+5VIOrzT2NsF9E7dGqUDMC6Etc1GcxhMsKTVpTHvdrIEKAresu3ICaOu+8R6tS366lRuhjzvFDvnNYJhqpOIcSKr+t5u9UHxFHPHmR8weZKcz4PvwiuV06ZBn25gFHeIfMfE4rUwSaHfROBmXaxcIJ/f82Ekjt+MVVT+gtCtD2wp22y4J8Jha28ajDib3/GMZT44Dt+GGoTTcnMrMGD6SENSFOWDloSbAQF5ZAnTWkP27yjqrKhqM7FEQH87vD2OALB6hWzt1sdSobA7jr1a2/zLyjIqMReqIUF5Se8Kxfg5ru9Vn+vTkGjgTDQT0obXh8/+m9ESg59hYW+B0ycV5V9wPS/bmqAzOdwvFM/k9RFve7js7AmVlaMdL/MxMC9keweVGT/4ht+vNs=,iv:o5SwYaAci4zZHfjn8r1jZv+0xcK0fjFb7NWOBp92P4w=,tag:B6qauRr0rUgeZuCVmDiBnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMTV6Vmh6Q05kTnRtV2FP
            cnBuSklaTm1WblpwNFhGTEkvUkhwTE9IZlVnClp1N2xoNmo4V2dxZkZvQ05pQ0Vr
            QStrOU5sUDBFMHVtVUNPNlNEWVRwM0kKLS0tIGwrNWhtbTI4c1pCaEttbDIwcXdE
            YVlKekYrajZ0SDVPTEF1RnVSSnFBU0kKs8CfIodIkWuFMS4bVtK6+loRRyKoDh+5
            ynIAiEFTGl3bsIjjo7+qw7fLGX+FwV2QMqOL6x1Xs+857iHbPDs+hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T07:29:42Z"
    mac: ENC[AES256_GCM,data:OWobv/L7P0GiILNQXxQj18mkorgg+7Xhz0WYed1I4GPn5uBFxBD4187RZ545uIWed9NpDG0HF/sIJzZb5fZJtfQ/rQhrWfd6cbowJ6dzU8qhIxnr4QHDjExHATkZjuslvB7ufhVshqxHyJ4q6zazBM1IzSQJFPaweJokOsyeJ6k=,iv:Cm7T0qhIOXMozSYKABE+6AWi9+7WKRSDxZpx93r4ALs=,tag:5a3LthPratKhDEeR1ky2Jw==,type:str]
    pgp:
        - created_at: "2026-06-14T17:46:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA4w2YNyo4oB3m9sZlFSJor4uz7SPT5FVVAVTAwHAbNAsw
            mkKtrnvOjl8iEWu8WfcBQWzK0kTT2YUVdBY4lwjjOaNKNM7XEzEq4jqlG7MII4HD
            0lEBykkI1EEs8/wVLUo43OkoYJk4IJmFD3CsTDXLYKEq3hROzg1d/nXddPdHxMgH
            vd9/IgOqqlXpDGZ83t4JCwj2dbojoCl+LdwGIiyUXXf98Co=
            =8poF
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.0
