apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: karakeep
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:9O0//T0FFbOjfw/uWG2hbOoM+4C9QYRpcYPBfWeWZxWj9R5ACSgEKCcCOCGZ24YbJocvQBTdgM29aZazl4DQ5xebY6W/uw5k8bwXpzlMBQDrnCYhBKQ/8djxjoLjn3JPWHkn1APrGYvElSSusF7lN/dBp5A1tL4bz2J6FfvSZLrUcJbg66U2HV6Q2skIia29TGe0a8H3pxy8gttBUPNWZr32F84nLArYPEwW3mV3WuUSst9eqTGeTNGqvJL+M3FzLcnQKAIW6SPHckHHPw8a2Iva/BgjPbyrOrturCmfq6QvhxGAfcH2HJiFjrvpxgHDuHoZh0JG2djYBx66FhQtElPAolyEwtqYfAdenM2Dpp1nHqL7EjGJXC2Y/TZ3mbu2T+92cjVCavfZlqmK/eWPBooOAh4dDVT6c4EqmjkblZILl+2wCncX9ymg84ZJ+aixJNMbmmmmYL1ivuJ20ujWidIWsnJnQLVv1eBJYyyK+abpUyfsSY3gEmNMz+9WiZtHXLpJjuMJ4P7aEaxuo5kg0TpLvE98pl7lwT/0uxXQuxCp4YJrBda54wjmJRaOqQlZBgLYEbEyyp9kxvyV+kjGj3RPj3WjjC+YgI7RNpnSMG0RnIGnd0smCqLdl1iUfS/sD+Dm6xAFuS9+Gr+485rPQtRJlVJyrKtHXVfJ3bw=,iv:fKzVj1a6IfXKC4T3vtXeXPdbjxjliMvIodeP2Si3AHY=,tag:00TLAzYyGHFiBfQtl2wrRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMTV6Vmh6Q05kTnRtV2FP
            cnBuSklaTm1WblpwNFhGTEkvUkhwTE9IZlVnClp1N2xoNmo4V2dxZkZvQ05pQ0Vr
            QStrOU5sUDBFMHVtVUNPNlNEWVRwM0kKLS0tIGwrNWhtbTI4c1pCaEttbDIwcXdE
            YVlKekYrajZ0SDVPTEF1RnVSSnFBU0kKs8CfIodIkWuFMS4bVtK6+loRRyKoDh+5
            ynIAiEFTGl3bsIjjo7+qw7fLGX+FwV2QMqOL6x1Xs+857iHbPDs+hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T16:55:37Z"
    mac: ENC[AES256_GCM,data:Phm4LJoL3/KqOkk5Llw1j7BkOOVOOlTSkk16uiTfBPqw4jNYIBCZWaRTMd3t3E/ym8Zrv622TpX+85xEtQPktmJGmyhQ9O5zCGvGRIkkaTnbKhDAjDJJXvCWm68PatHgHsdvLUxybSpcWPJVXRaUj+GzxloVY+b2TbjKQlnlyyU=,iv:nslnRPh0BkoS7UlbxTUb+mb0mWm08gjoQUnQvc8cTrc=,tag:JkI3e7MdKYwLK/5zm6dgnw==,type:str]
    pgp:
        - created_at: "2026-06-14T17:46:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA4w2YNyo4oB3m9sZlFSJor4uz7SPT5FVVAVTAwHAbNAsw
            mkKtrnvOjl8iEWu8WfcBQWzK0kTT2YUVdBY4lwjjOaNKNM7XEzEq4jqlG7MII4HD
            0lEBykkI1EEs8/wVLUo43OkoYJk4IJmFD3CsTDXLYKEq3hROzg1d/nXddPdHxMgH
            vd9/IgOqqlXpDGZ83t4JCwj2dbojoCl+LdwGIiyUXXf98Co=
            =8poF
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
