apiVersion: v1
kind: Service
metadata:
  name: lldap
  labels:
    app: lldap
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ldapPort }}
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    app: lldap
