---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trilium
  namespace: trilium
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/trilium
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    nodeSelector:
      topology.kubernetes.io/region: oracle
    service:
      nodePort: 30011
    persistence:
      enabled: true
      storageClass: "juicefs-oracle"
      size: 100Gi
    envFromSecret: trilium-secrets
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
