apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-db
  namespace: authelia
spec:
  instances: 1
  storage:
    storageClass: local-path
    size: 5Gi
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
  affinity:
    nodeSelector:
      kubernetes.io/hostname: oracle
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://mts-postgresql-backup/authelia-db
      endpointURL: https://s3.us-east-005.backblazeb2.com
      wal:
        compression: gzip
        encryption: AES256
      s3Credentials:
        accessKeyId:
          name: cnpg-s3
          key: cnpg-s3-id
        secretAccessKey:
          name: cnpg-s3
          key: cnpg-s3-key
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authelia-db-backup
  namespace: authelia
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: authelia-db
