apiVersion: v1
kind: Secret
metadata:
    name: juicefs-secret-oracle
    namespace: kube-system
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:HixiECurhd8dQKmWtr8=,iv:S7s+j5p2PSOgMThKk9RtETWe5asm9oeqyBzvpH4NLco=,tag:CHJR+44Yha8pQBJyoxJ4+w==,type:str]
    metaurl: ENC[AES256_GCM,data:tcw+i+JKNhRgTCEVH/wvsALeZo6GTjBoV8U2zxCZnr0REZp752cOeJODKlYwr40LL3815eb/UGEi+l/y8ra8ISwHi70hMchZ,iv:LQ423FRNmfFahVsORirJhRQ3I+ic4RsIv+SO+RyIxRo=,tag:z8KisRExTCv4r1yO3enfUQ==,type:str]
    storage: ENC[AES256_GCM,data:VDM=,iv:rKfRb45Ojgq8+s+XPjtMfLGzMyqr6d0xGEGtkhDqYjE=,tag:i+lJjQPNZJE8nYiI+lqcwA==,type:str]
    bucket: ENC[AES256_GCM,data:MDsh5mRczmQELXmx57YXaC6oNyKePkKRt54bOYaa7A+d5fOOAnj6wvfzdfcZRpcAchs0wm+H,iv:QE9a5PSkPB0M9iDK32E2a2Hxjjgawzw3EoHWKJeOHmA=,tag:7qCHH9GrUCXcIyrsOLJL1g==,type:str]
    envs: ENC[AES256_GCM,data:1ydlkod9Nwwr/zqKT9nfMTmx7aYKX7gb,iv:yMuSXTdE6fLC1QOma2Te9Ufj1Ag9AtRgDPRwPZ0XUHM=,tag:1mRIJm8OF6rxZvUWOX9kMA==,type:str]
    access-key: ENC[AES256_GCM,data:rsZSRpOw3/nzW5pd2407b5XHkPeoxQqT5lE=,iv:NVanQ8XYJaF8JWROiNV9Bbd3u8RC7kEZ5DSuNRrL6gc=,tag:YTePvWcwsK05vCdfSQo+wg==,type:str]
    secret-key: ENC[AES256_GCM,data:leN8oKOoM/bwqpX/vqNqo9ZYP9C/nYTeZWqBK6Vn6cTpHLttPbSK8WPYiKyxPZFWGFplKQRHOyHc4is6D2j7rg==,iv:mHO58I8jhRyFrkEP4CJMbpbMBiYyjVtfLZKfv9Dak8s=,tag:cUnm5rzn3gHlY/w3ZkJF1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS1JFSTFBRE1zcUN4MWF0
            eisvaTZtNFhwUHJndGUvVmhPbTFCZm1SajB3ClB6b1ZNeHBNamQ0OWdJeWdRUEVS
            ZHYxcGhjaXREYWk3WlhlWDNPa1B5M1EKLS0tIE9tVVMvSmZnTEsyS0xITXFEUDdQ
            YUhzWWVBZ2l4K3A0WGVXVGNINE5MUkkK7NO43P79XOTbynxn0MAaEYKxIH6/Z9Fj
            oOI3/HZ2YWfIghnkLEcMJUpDzn7zPrjYoGgpHFOSJ0+wWHiMWsUqFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T10:36:13Z"
    mac: ENC[AES256_GCM,data:NDpSN3j4U9fDBsEa5zb7B3JTrB8P0i9A6AiV4VKPxh30mK/BQxrNHflB8GuOJUN4VmjbQsIlCPoT+e74Sjhk+2FYbzXxo6JVtGU6byWx7rISyQmnDlgHSGpt6jS/1bxrSGD3DE6k2K7/Vfa/QA451uHXaAqy9C0OTcwx34t/ecs=,iv:40r3A7o95GUfKlXFAOfcH34NHHaaLUzpUoSV1ENZzsE=,tag:+5aPOZE9jLiWOf1C6Dc1gA==,type:str]
    pgp:
        - created_at: "2026-06-15T10:36:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAYz6REeq57mTwu3vrApsr3LWXE548Rt5d0VIEKmeaRRAw
            1gpPoK3A1CpZq2P4gOrvDyj2hhEb66erp6jM40ebP5aZwpZ/FdsVX2oLpwaWUSU+
            0lEBJZ/Sc11aHUKDi4D8DicBPBCYM7OJi89KZdYFsEzjyDioh+8KODSFI6aWkE/R
            aEmEURtvITxJMWzaWBF83PSIiLCan+7MmSzuRqkgX+jr0k0=
            =kSro
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
