apiVersion: v1
kind: Secret
metadata:
    name: juicefs-secret-oracle
    namespace: kube-system
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:HixiECurhd8dQKmWtr8=,iv:S7s+j5p2PSOgMThKk9RtETWe5asm9oeqyBzvpH4NLco=,tag:CHJR+44Yha8pQBJyoxJ4+w==,type:str]
    metaurl: ENC[AES256_GCM,data:tcw+i+JKNhRgTCEVH/wvsALeZo6GTjBoV8U2zxCZnr0REZp752cOeJODKlYwr40LL3815eb/UGEi+l/y8ra8ISwHi70hMchZ,iv:LQ423FRNmfFahVsORirJhRQ3I+ic4RsIv+SO+RyIxRo=,tag:z8KisRExTCv4r1yO3enfUQ==,type:str]
    storage: ENC[AES256_GCM,data:VDM=,iv:rKfRb45Ojgq8+s+XPjtMfLGzMyqr6d0xGEGtkhDqYjE=,tag:i+lJjQPNZJE8nYiI+lqcwA==,type:str]
    bucket: ENC[AES256_GCM,data:s/dT7MxMSrnETfyn7JPGyVWT6pwnxCNSa0YWw9xQxflUDinBJreX14PvN9/lWtNv1S0E3YeU,iv:dQ+wx5aMsk/IAPcT8AIwsvXKxlW1Pzh3rPyY4zqgPsI=,tag:+CK7PcJ8+kEsvGWCCyamZQ==,type:str]
    envs: ENC[AES256_GCM,data:1ydlkod9Nwwr/zqKT9nfMTmx7aYKX7gb,iv:yMuSXTdE6fLC1QOma2Te9Ufj1Ag9AtRgDPRwPZ0XUHM=,tag:1mRIJm8OF6rxZvUWOX9kMA==,type:str]
    access-key: ENC[AES256_GCM,data:t9O2bSxLN20sk7imn47nsFjA5145X/5ovbs=,iv:0seBcO42IabO57nV8uqBMRtXa3E7eVRvz2vozakOcBg=,tag:mwM9LcbvFABSY0FOsZXSNQ==,type:str]
    secret-key: ENC[AES256_GCM,data:USfW0DQ6B4LVEwN7lrwcJh5u6RoU/R1hkxGTVJPOVaDCYqOCbzoDwzTD/+0RwnkUJWlrO+Epm3mE3SYmC/y6WQ==,iv:0XNtbxn0+wGR5RDXkLe/n7z7QW3PZiRmyS4h3YM+Ipk=,tag:BmZecOSWPuHi5slCVqT0sQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS1JFSTFBRE1zcUN4MWF0
            eisvaTZtNFhwUHJndGUvVmhPbTFCZm1SajB3ClB6b1ZNeHBNamQ0OWdJeWdRUEVS
            ZHYxcGhjaXREYWk3WlhlWDNPa1B5M1EKLS0tIE9tVVMvSmZnTEsyS0xITXFEUDdQ
            YUhzWWVBZ2l4K3A0WGVXVGNINE5MUkkK7NO43P79XOTbynxn0MAaEYKxIH6/Z9Fj
            oOI3/HZ2YWfIghnkLEcMJUpDzn7zPrjYoGgpHFOSJ0+wWHiMWsUqFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T13:38:02Z"
    mac: ENC[AES256_GCM,data:bmA0wVJ8i3uL6l0o1unnVQDYhpFPX6Se2l+Mc4cH5afGIDmqjfScXdjXyuko3jibU0LfeTzEZeDPog3UPge46Cjk1jHPQo94VQouuTPpjuF4ah8ioZTNpdlpd4DgRvgdJ9UBoycDd4gw9sEdBz9TPTbg7ftA+4eJelc8jaJJQY8=,iv:bwQOfOhzcd3rcwdcQRZUtbj1sXaeRNDMOS35oMzmCRY=,tag:HODaUpyW5vICHeZ8x1/W1g==,type:str]
    pgp:
        - created_at: "2026-06-15T10:36:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAYz6REeq57mTwu3vrApsr3LWXE548Rt5d0VIEKmeaRRAw
            1gpPoK3A1CpZq2P4gOrvDyj2hhEb66erp6jM40ebP5aZwpZ/FdsVX2oLpwaWUSU+
            0lEBJZ/Sc11aHUKDi4D8DicBPBCYM7OJi89KZdYFsEzjyDioh+8KODSFI6aWkE/R
            aEmEURtvITxJMWzaWBF83PSIiLCan+7MmSzuRqkgX+jr0k0=
            =kSro
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
