apiVersion: v1
kind: Secret
metadata:
    name: juicefs-s3-gateway-oracle
    namespace: kube-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:S4zcmzu1KJXT7mYxY4X+HTO4932qke7+c6MBL3NJsS2CcOlkQkBUu0sgurX1b5Oz3uHFTxaHBdC7lTEaGOZXS619WavjB/TOHBcrzWTpvDRYSNWolkI/ZFrNGCMfFkVAQUQukPWCJloMI/aZHpK/KupJ1BtC2SnVuVRXiU2WUtUeMnXUz5VOhjjXI82ePE0bj62VI1Hc1rBMYFzm60n1lgbmvwUfYAEBCAGfkFjm46+qfl5NislMvCzppF6nt+j6Aj8l2bzzCO2w9pdu2VomCiI+DLmZv75+Lx204/I5zeOrdqsjznUU287g71VH0rg6Yfqf38YXky4nT8onx89jvg7OUFy0CpY4S6gjByVb8O7cKqbyPDAk5SDjysBzu0aZbXlawGMc+jztY87/bA==,iv:9ZcpCAbTxfa0/RRwJSu7mL8DoK6nvq6JkkzMfigwipM=,tag:s5FpOMvy4lZTk+4weNaNBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCY1FhY1dySVUvZjZKZmtK
            MXhrYytzRG4xb29Xemo1KzBidkZwanJJQkFzCmFwVDFqajN5Mmo0ZFUrUlpmOHBN
            VXZ6QlN0dDhldk0weG1uTmdPY0lkUE0KLS0tIDg2dTI3WTIvaXF3NnduU2VGaGtS
            MU9WS1RyUnBnRWp5Nitoc1hsWEtqVVEKrHw8nufzXWg0SoG/JLAU7YEGsmRVaQGs
            gCbFA1TiNxRgK9VcHrdsWVrRaS7AmNzU2TRap9NEY01uod1GCEjucQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T07:49:57Z"
    mac: ENC[AES256_GCM,data:j5bPbIvI5cK9vK1U5UA1dUr7AoZWWcLrQADP7G/CIK7ZffsRqdrrQPAVtychXXFkmlIbEPnjmJhUU1/5N/Pv4WN5qA6G0Sa8Mz/5PEgTf5j0FgEqvKwFq11NimMdfsOTiYFDN8odEsbt+TOpgpPPZbreXcx00IK96QhJiURLo8U=,iv:z6WMoHwBc1Ucv8P0QtVvk6xJoe3sbgC3J3gSKg6yVtg=,tag:uP7gtms2qJKyzafvWBScaQ==,type:str]
    pgp:
        - created_at: "2026-06-24T06:54:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA90fusalHxRoqq+PSSvK7FPOuJXRvXygxA0kBvFmtywIw
            bdv0p9nxbjJoiFeD7hZ4918XpPq2QLvonSq2fCCEBux7pitQNV2fpL5qJQoOWIOP
            0lEB6VHkQ9VD6uMCIbOqO/yFuclIsSuekj5fNC81dmQ9sj15thZdFPkkvNSkq8kr
            Xr1vsfxuEu6MEt2DCzaRNlFr4o5hLrSNTREXTQEA6jiqg6s=
            =Rru8
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
