apiVersion: v1
kind: Secret
metadata:
    name: juicefs-secret-homeserver
    namespace: kube-system
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:6y/TSEZQDKlGK8oAYomSrSGX,iv:hZH+m0EI5D0L9HZScsLPvDiQxtKJJTrAj8MzpGFGNgI=,tag:oq48ZScZgfkb8zE8PxbGYQ==,type:str]
    metaurl: ENC[AES256_GCM,data:1C7Fb0z/jhcOj0Y2eYGvJFhDhWnCKk4yEpovEWheytAncdHNiLXVQpOEoRve6Nlaet58BuHzEH7sx/+LmTbVh6QiAz5Jqs7rctJsxg==,iv:XZlrAZ9i0BNa2CSG+KHb3dFhGFNiw8TeAvqKzxtD540=,tag:P22h3ng9rLBG53Cm14grVQ==,type:str]
    storage: ENC[AES256_GCM,data:nJw=,iv:3I/kOZTltkTtp4iM144yBmJX5UGwFUMhenBvS7SV4+E=,tag:t+5drikYLzKW3Q+piOFdOg==,type:str]
    bucket: ENC[AES256_GCM,data:JAXV9P6g3qI/zJrrXxtY0eDouzz8Bj0ekuMAdGiVZ0EXQVXsSl/0+WOwFi6Slw0=,iv:VdO6cUp24Desd5g8m19DnbdJ0dwZrq5spkCcuO99fEI=,tag:1wj1zQL5jF9rb0cuDvD+qw==,type:str]
    envs: ENC[AES256_GCM,data:MDiXwCb4kSgfYhh23YeCzvbBbr5AF7Jr,iv:2K3kCVUwMKTWmBfo7I5lncJXwqxkFMu81fY9mVGo2Yo=,tag:M/NXuAV8i/0Uv+19V86nDA==,type:str]
    access-key: ENC[AES256_GCM,data:N0h8wlgXTCMbg7DYgOTKR+ZXKbsm5iyt/AI=,iv:QAh2Cgx5Ijb3cq3nJ6KYP74POdVsDllBXsPLdjuWm6c=,tag:1jiipELIi7UO0IUYez2tzA==,type:str]
    secret-key: ENC[AES256_GCM,data:PCNdUWlFJnPi7/JuetXxMvDrB9mwf9NbDkj1WBOoUZT6ZSSjdjv/bD5O6rrB4/Hk8hM8D+mqLjrlvKwJZbUIlw==,iv:4Q1M9aLeQlCmHqvxJ052PMDErvG7JgJMnLlkZjfoVSY=,tag:DW8tFLTzKt+ykSz+pCXU6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUjc0Nlp6SlBWYzgraXVV
            LzhyRU5NWXJiL01HWkhEU2NMYTZlNFpOOTAwClAvY1dDUXlSTERLVjk2WENyUzVS
            a294cVhqS3hDYURVSmtxSFIzQjVrK3cKLS0tIHQ2ZkpoNmgvZUt6UlMrZFBrSzVQ
            UmJpd1JsTkFTOEZ3YXZHN2FoYXMrUGsKqDUcNLgtM0MGPzEa5v966Q2kF4jgtkVN
            bqYZC6g/TdVnhbv3zFineHM8jNiOKv9xv+7pVE/2SQDckqldDdOMWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T08:29:36Z"
    mac: ENC[AES256_GCM,data:9XXvjv8br44qN5Mv+hdD85qEKxgL3YQIERVOtWIAhG5ElwYv73AGSat5lOKNySIeBPDWEqOlQk197vuZ1opBZdfxk/3vL79VsY/x7ZmOGm/1ITTy2Rye+0o2cP+Q4QfkAgzFSkWADx3lDntBukTnPL/GN3WNwG9HwudG8Kxef1w=,iv:BZDu+Kv9UnGlNjC3h1o1Lw5CKrFq6Bid9BzDRrULr38=,tag:3kQv9TCz1A7SlFZ9Ju9a6A==,type:str]
    pgp:
        - created_at: "2026-06-15T10:36:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA/1wq5cbbzVgtB1h0Otor05kaUROzid9dKKlO18s2hFcw
            dk2zWjl0p3traMZjo8qd0MjLg79uTr20A4RIc//1ngUkTEJ3y1v5VtN2cEqny5XD
            0lEB5zdlTFw1cDYCxmaYmHgYZupy8SYbb5eIkPBpRneF7FYAP1pqTFuhB4OoTsac
            mn2wxzKEptSO0yQdgHC2mG4nXglvZ+sb25zj4oyIPObA5PA=
            =b0vT
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
