apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: kube-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:regcnmOnoA2AnLZU/DemYP3uLI2NsyZzKjUYZ2S7OxIIueASoe6A2J1wLGNBx5CW7PACs2KGY/61a5/x/UeqcigskT+rcLfMiadqM+N6ENGX91sktU5zwU4L5m7T/7e1zco8twZM+PoO4tO3DcjYsBggyoiTcwrMvt1FecFUKkRT9bQ0PCzvy9nICwy65h8zp8xvG62qDimL+Oy2jahGwr/DILJjroX1LYpqlYp+FT6LtmdjBqhPHWzc0AkTJXkmAPsxsuVQiimXWesvIzHFzfVH1iL+Jda3Q2MZp2O4wBXNTyqinHPQ7tqUKUe3USEtDoOO9QHeIXcLkkDxTdrYK2gsqyohdcaoGgVrjIobai7L7J0wpG8Xxa7Q9Xtp7a6aNAPxlWzfsbr/+M3GVgYPy8yMELV8OZdDksHXyBWwUcU15QdhLyU+6b4VtFeoovSXmYcpiIIaIVyWOw0j0QbfhXW8GK0LPqdfR1QuDFiebJ2bmej9lKxvojstx8fU9OpcBPwxjrN2iugFzQWWzdNET2+6IOvPhHcEdQpfbaRoZ1zBJnleI8HUZZQ1r/Aj54VZZazYvfxDqHJOuaI59Rhn534FKtNJQpQKug==,iv:0ES89RTOKOO7VwInII+VcihOSCKXRJPVCfN1EuG0tuM=,tag:siYxsj6pgVfIN5lPspBuGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCY1FhY1dySVUvZjZKZmtK
            MXhrYytzRG4xb29Xemo1KzBidkZwanJJQkFzCmFwVDFqajN5Mmo0ZFUrUlpmOHBN
            VXZ6QlN0dDhldk0weG1uTmdPY0lkUE0KLS0tIDg2dTI3WTIvaXF3NnduU2VGaGtS
            MU9WS1RyUnBnRWp5Nitoc1hsWEtqVVEKrHw8nufzXWg0SoG/JLAU7YEGsmRVaQGs
            gCbFA1TiNxRgK9VcHrdsWVrRaS7AmNzU2TRap9NEY01uod1GCEjucQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T07:15:08Z"
    mac: ENC[AES256_GCM,data:lwptgDG3yacSW+mFj7KMNuFfEfjAIsWyvQqVJkJYscmm1w1l2L9zTjpPX3VDtVfRJEY5QOtVpg460hQQNIqgeBgQbcHwg2UJVUlBb7yzR0NmkRMvLVN/o9S5YKJYuXB2V62Id8HeQsj5M+5/6h87PGn11uQSVeGbrZDsimyAGXE=,iv:+x9kPl0nMp6bt9eJck9eXjf7xWGhBQ3ZtJVmbv4No9M=,tag:4gs/ml5Cy0834t1tYozSbg==,type:str]
    pgp:
        - created_at: "2026-06-24T06:54:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA90fusalHxRoqq+PSSvK7FPOuJXRvXygxA0kBvFmtywIw
            bdv0p9nxbjJoiFeD7hZ4918XpPq2QLvonSq2fCCEBux7pitQNV2fpL5qJQoOWIOP
            0lEB6VHkQ9VD6uMCIbOqO/yFuclIsSuekj5fNC81dmQ9sj15thZdFPkkvNSkq8kr
            Xr1vsfxuEu6MEt2DCzaRNlFr4o5hLrSNTREXTQEA6jiqg6s=
            =Rru8
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
