apiVersion: v1
kind: Secret
metadata:
    name: traefik-env
    namespace: kube-system
type: Opaque
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:L9IgntZt7RktXxv5faIP0w1Q3oiKwMok4uVRSBW6Zm0kSsojuo9gnbzhVxNgf4jL7Qz5+Tc=,iv:KCnGMkIkcafMA1oONbD3fN9jGgRHoY8QEIufvz+voiM=,tag:1EDMNrPZdS3BLJbt96UcpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcmQrTGJWN21ncVNTNDFv
            SHVLVkJ4WTdoc2FDOGhBN3BJM21pTU5JRndRCktEZzBFZHpLZFp4NkpHSmRFOVFO
            aHVLcmVGN1JGbTBqMnlZMjFpVWpySlUKLS0tIFd3OU9mT3ZIclBWQmI1LzR5YkxT
            eGgxakhkYjlzZzdTZlZQeGpXcHVKa0kKCPTRjSEQ5W4WRH6kiFjmGUAywmQE78NK
            POvh632JkXWbfbMctj/9y0MzlyVMFSGW6Wc/sABlP8H4rM4Ibm9hZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T15:28:07Z"
    mac: ENC[AES256_GCM,data:IhoEBz0CbfH0k8kKaY4hXJ3+GpNeYg8cgWeo5LFgQ/LGX8Qtn77MsP+1tIIFP+OnFCYW9NiPX1XwodikFP76BdZ+NXSM3KlZgmt+e6dsawnQ9Tmf+Po8D0ta0BYaG6tx6Uhn2iZwSBDbflDv9Wh1EA+Ix4E++9DicJOJvWo0xPY=,iv:yxR08Vb5v8t634Ha9mKrAX4xMuEGFCuHd5q0jtpYY+c=,tag:EM2OvKgRP8ED7phjHhHgLg==,type:str]
    pgp:
        - created_at: "2026-06-22T15:28:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAuWSB9a6jjpgqf39gGpQlX2YSEJacoYQi5OmH9/WuwBcw
            dZ5W2feampw8QbgxPSprGU6vVscIB4aX2f+ClIBISF0z4RuVG3HLADGy2BhrWRVi
            0lEBki6NI48d4xoq2R5I7C1uvjsOkGZIg5aJRVkKiszcYWlPNYmkkGdHkgjf7s9w
            BC22vCFq1QJvAHA6eqgWnACpT9buVowEZXYE3kQRwGeVH2k=
            =l85V
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
