---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: kube-system
spec:
  interval: 10m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: kube-system
spec:
  interval: 10m
  valuesFrom:
    - kind: Secret
      name: helm-values
  chart:
    spec:
      chart: k8s-monitoring
      version: "^4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: kube-system
  install:
    createNamespace: true
  values:
    cluster:
      name: k3s
    clusterMetrics:
      enabled: true
      collector: alloy-metrics
    hostMetrics:
      enabled: true
      collector: alloy-metrics
      linuxHosts:
        enabled: true
    nodeLogs:
      enabled: true
      collector: alloy-logs
    integrations:
      collector: alloy-metrics
      alloy:
        instances:
          - name: alloy
            labelSelectors:
              app.kubernetes.io/name:
                - alloy-metrics
                - alloy-logs
    collectors:
      alloy-metrics:
        presets:
          - clustered
          - statefulset
      alloy-logs:
        presets:
          - filesystem-log-reader
          - daemonset
    telemetryServices:
      kube-state-metrics:
        deploy: true
      node-exporter:
        deploy: true
      windows-exporter:
        deploy: true
