# Default values for karakeep.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeSelector: {}

persistence:
  karakeep:
    enabled: true
    size: 5Gi
    # storageClass: ""
    annotations:
      helm.sh/resource-policy: keep
  meilisearch:
    enabled: true
    size: 5Gi
    # storageClass: ""
    annotations:
      helm.sh/resource-policy: keep

secrets:
  nextauth: ""
  openaiApiKey: ""
  openaiBaseUrl: ""
  inferenceTextModel: ""
  inferenceImageModel: ""
  embeddingTextModel: ""
  oauthWellknownUrl: ""
  oauthClientId: ""
  oauthClientSecret: ""
  oauthProviderName: ""
