---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: affine
  namespace: affine
spec:
  interval: 10m
  dependsOn:
    - name: cloudnative-pg
      namespace: operators
  chart:
    spec:
      chart: ./charts/affine
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    nodeSelector:
      topology.kubernetes.io/region: oracle
    persistence:
      storageClass: juicefs-oracle
      size: 100Gi
    externalUrl: "https://affine.rmtt.tech"
    database:
      host: "affine-db-rw"
      port: 5432
      name: "affine"
      secretName: "affine-db-app"
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
