image:
  repository: triliumnext/trilium
  tag: latest

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  storageClass: "local-path"
  size: 5Gi
  annotations:
    helm.sh/resource-policy: keep

nodeSelector: {}

env: []
