---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karakeep
  namespace: karakeep
spec:
  dependsOn:
    - name: authelia
      namespace: authelia
  interval: 1m

  chart:
    spec:
      chart: ./charts/karakeep
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

  valuesFrom:
    - kind: Secret
      name: helm-values
  values:
    nodeSelector:
        kubernetes.io/hostname: oracle
    persistence:
        karakeep:
            enabled: true
            size: 50Gi
            storageClass: "juicefs-oracle"
        meilisearch:
            enabled: true
            size: 10Gi
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
