apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: authelia
          image: authelia/authelia:{{ .Chart.AppVersion }}
          env:
            - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authelia-db-app
                  key: password
          ports:
            - containerPort: 9091
          livenessProbe:
            httpGet:
              path: /api/health
              port: 9091
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9091
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-file
              mountPath: /config/configuration.yml
              subPath: configuration.yml
              readOnly: true
            - name: authelia-users
              mountPath: /config/users
              readOnly: true
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          emptyDir: {}
        - name: config-file
          secret:
            secretName: authelia-config
        - name: authelia-users
          secret:
            secretName: authelia-users
        - name: data
          persistentVolumeClaim:
            claimName: authelia-pvc
        - name: tmp
          emptyDir: {}
