apiVersion: v1
kind: Secret
metadata:
  name: authelia-config
type: Opaque
stringData:
  configuration.yml: |
    ---
    theme: 'dark'
    server:
      address: 'tcp://:9091/'
    totp:
      disable: false
      issuer: {{ .Values.config.domain | quote }}
    webauthn:
      disable: false
      display_name: 'Authelia'
      enable_passkey_login: true
      experimental_enable_passkey_uv_two_factors: true
    identity_validation:
      reset_password:
        jwt_secret: {{ .Values.secrets.jwtSecret | quote }}
    authentication_backend:
      file:
        path: /data/users_database.yml
        watch: true
    session:
      secret: {{ .Values.secrets.sessionSecret | quote }}
      cookies:
        - domain: {{ .Values.config.domain | quote }}
          authelia_url: {{ .Values.config.autheliaUrl | quote }}
    storage:
      encryption_key: {{ .Values.secrets.storageEncryptionKey | quote }}
      postgres:
        address: 'tcp://authelia-db-rw:5432'
        database: 'authelia'
        username: 'authelia'
    access_control:
      default_policy: 'deny'
      rules:
        - domain: '*.{{ .Values.config.domain }}'
          policy: 'one_factor'
    notifier:
      smtp:
        address: {{ .Values.secrets.smtpAddress | quote }}
        username: {{ .Values.secrets.smtpUsername | quote }}
        password: {{ .Values.secrets.smtpPassword | quote }}
        sender: {{ .Values.secrets.smtpSender | quote }}
        identifier: 'authelia'
    identity_providers:
      oidc:
        hmac_secret: {{ .Values.secrets.oidcHmacSecret | quote }}
        jwks:
          - algorithm: 'RS256'
            use: 'sig'
            key: |
{{ .Values.secrets.oidcJwksKey | indent 14 }}
        claims_policies:
          default:
            id_token: ['email', 'groups', 'profile','email_verified', 'preferred_username', 'name']
        clients:
{{ toYaml .Values.oidcClients | indent 10 }}
