apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
type: Opaque
data:
  n8n-encryption-key: {{ .Values.secrets.n8nEncryptionKey | b64enc | quote }}
  runners-auth-token: {{ .Values.secrets.runnersAuthToken | b64enc | quote }}
