apiVersion: v1
kind: Service
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
    - name: http
      port: 5678
      protocol: TCP
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
