service:
  type: ClusterIP
  port: 5244

persistence:
  main:
    enabled: true
    storageClass: "local-path"
    size: 5Gi
    annotations:
      helm.sh/resource-policy: keep
  userData:
    enabled: false
    storageClass: "local-path"
    size: 5Gi
    annotations:
      helm.sh/resource-policy: keep

nodeSelector: {}

env: []
