service:
  type: ClusterIP
  port: 5244

persistence:
  enabled: true
  storageClass: "local-path"
  size: 5Gi
  annotations:
    helm.sh/resource-policy: keep
  db:
    enabled: false
    storageClass: "local-path"
    size: 2Gi
    annotations:
      helm.sh/resource-policy: keep

nodeSelector: {}

env: []
