apiVersion: v1
kind: Secret
metadata:
    name: filestash-secrets
    namespace: filestash
type: Opaque
stringData:
    gdrive_client_id: ENC[AES256_GCM,data:urQapUUJnlGhvgsEUExcAXexXJeY7LpBqLCYC90wITK+PlKNJsQB/ovRyfG3sdyrFq0kf32cJvY0tsU/qRf71KDMfRxSrwvw,iv:iNo0MA8gv1qOKhNZLi/FoCheIBWaSvE6FNcCL6UcJvQ=,tag:H+/s06UTckqK8TOljZVXJQ==,type:str]
    gdrive_client_secret: ENC[AES256_GCM,data:xP/2SHOLVAolXpZ63JvCy09ykg4/qaVXMNpnwfAINj/jJY8=,iv:V4QmhODisHscqYHlJjcldR0s+ifGJ5wvRgPZWc38UrA=,tag:cZAl5Lb1WNuyyCSs4XjIiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SW1WUnBXcHpmTDhzYWlu
            RkFwVlRXaGo0dnBDVDh5N2NHd3VtUWUxeHdNClQ0aVVRNjhjelZKZmtoK0RGeCtZ
            c0xXUnY3QjRsS2U3aU1FOUJ4d3I5T1UKLS0tIGVOV09Dek0yREpURmNhOXB0Zjhp
            TzkwQzlMSmhNSUYrOEJXYUxyQk1sb2cKWEA7Ol17pSSFs02+W+NGaWnWlCZ4PjpC
            O4tZ3D6h+Uch3eEqTH6pvxEqB2K6KCzb7lK6pzHD+xTitj9ZdH8eqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T14:09:03Z"
    mac: ENC[AES256_GCM,data:BaS4k8QUMK8Skr6Ca0hEa29FCL3mtMuNpHAjj7xvXdkV/UQiJ9KChfmzjR/xlU4A2UEYlfP/AzFbza/kwlEGAdrxLDat9a90Z+xuygkdpLV4udvdn6R9/98rn9uYopQgL0fey8B1Mb/f7W2lbD6G8xegp1/ZH8loIz4QuqRvLW0=,iv:vlx95rvTPbhO3cB38DvpgFa5l0yn2T1QBLv1BHL97pI=,tag:BZrwrRq99E0VNL9hY5vS5Q==,type:str]
    pgp:
        - created_at: "2026-06-17T13:54:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdASx7ctF0jOmJdvQwSlXo7LJpPDc2Gmc3GJ4fFim2NdQww
            QQ6Agr0oVdEF8ol68gcULBSLT2Bqa9bAeENoEpim4Wc4PUMyTRPNp2t2zW74nJNd
            0lEB0NVclJOgFoZ/Ogz9RgSzQvYw3cZCGvCqz2F3V6ZZWQmPYUF88K1+6KpG/5I1
            9PfxMomFyf5bjDdCIjMkhuYTc8hEKZyN2ys0LhpUJcKSdmc=
            =0y4k
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
