apiVersion: v1
kind: Secret
metadata:
    name: filestash-secrets
    namespace: filestash
type: Opaque
stringData:
    GDRIVE_CLIENT_ID: ENC[AES256_GCM,data:k1bKvZMRZeimSxsu+rXsEQz51erg0Uz5SZiVpMmOx6z7jQv1oqeivZz7XeMmf38tt2UvOdWckNry19MkoZsNQmMZnNr05Ppn,iv:nBuWcfFrhePCasJV1R/9oOdIrHQDQb2yAdZsXlnZrSM=,tag:DepsVK6yFZ7Rtz9bb4aEow==,type:str]
    GDRIVE_CLIENT_SECRET: ENC[AES256_GCM,data:463btlZWkZP3QayDRf7K0pM7pi60yNvWoAG5jqyBdeALfGQ=,iv:2OU/GzIhbpgPiYbveRKnMYQqOW/JqU8WburVR6JeT/4=,tag:FuKkxphQSz3YpA+pSBWRdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ1dCYkFhUi9aZlRTN0VN
            Z2lVOFdGdGFxdFEwS1oxYTMvV1EvWlNEelZjCmF6S0lDWUhBQ1k0cjc4SWxyOTEw
            dVMwWTA4cGRTSzJtbHkreUd6T21WV0kKLS0tIGE3NHVmSWJJZEZvNUloVkpxaVRW
            THo2VTFFWEV1cUJBM092aGxmbjNNcUkKopUimhlDBUisA9NiPuW+AJFt1ghiDzrh
            GbrqtQ5g2kA8AOqf8B0Px+g93sEZqE6nW7fANwW0eLDUen/JfVbxzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T08:20:25Z"
    mac: ENC[AES256_GCM,data:cKOhhpy7g0/41KnI03VOlc8Bxq+Uk9jRtRB693mk4a4cYYojzS7uSSDmPpz8JW3m+5aIG317AqCvWUrBHPvCPNEFDmEg83vW53doi7FTnlxHMStyP4HWy5j+3Iu7FIl/XX//XjjeAwO3fuGCvjaCTLbYATA4kQ0Up2fdoRcpQ+Q=,iv:tCgK5jriYaoWAeuklQ3VQFVodOHrt+Cx2nd2ioVwyEw=,tag:7JoCJHc6wvBYpUMH5hd44A==,type:str]
    pgp:
        - created_at: "2026-06-23T08:20:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA0tB6e9BxRqWeqYfEI5jCCV2hVjNp7XGo7BQGu0oT8Dww
            ajEficfQgqk/QSLN13NV9fZUF+DuMXs2P4o7QoHnaa1woI8IQcjG/jFSxIKyyyeC
            0lEBwHXQuM+EmzFV42pUPeg6mEFkkPkIsVzTPS8CQoQpdy7wFZPNlmYI8GeYS9+4
            puXCahV/lcGz9IG9hebEmcRYXgT15hxbTBg/Ca+PV+ZU0VY=
            =IdmS
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
