apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3
    namespace: miniflux
type: Opaque
stringData:
    cnpg-s3-id: ENC[AES256_GCM,data:c0JwC3GCqvIIr/bcmcG4LouRZzPPXg1RaK4=,iv:gR37BuVGoCpafrsFhO4pVSXE3aWhUsm2WBFVor5aQt0=,tag:tdJ0OEH4zwbIZwBxDg7GBA==,type:str]
    cnpg-s3-key: ENC[AES256_GCM,data:TJqlUeBGNgpkVb3AcXVbJ49nWVAk9WGddqdOL0Envh5giacpVHDYNwZT8lhXY6KBLUqwMmEK9D/V0nmNjp8q4g==,iv:nsQAghGTAnhp4GqA7lVRlZKjQGCBqgV3DydJsZlYqFM=,tag:hvTtffANt1jkjccBcAXQwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQUIwd3daRE1Pa1ZFam1t
            SG5aeHI1Zit5cm1mamxTVndHZzd4WE9ZbGhNCkN6TWZkbkRnSnJ5Z215OHBBUUJS
            c2VvbG53ME0yK3NkWHJGUkxsQ1JCVHcKLS0tIHVYQnJ6SG50aG0vNkpsQ0ZRU0lt
            TDFNSENqV09BS2lKZ3JvN1RBTFFVM2cKbENBsI/1j38yFBb98fhV43dGHdo+9JqZ
            vo1bBLW14QjQLgLz/n8vQ3xMplvTQMWwIYJePgeVtoGQCekhnC7nxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T05:56:56Z"
    mac: ENC[AES256_GCM,data:SGCzSt8wQLuR0cEAdQTfgX+mkgOVvFsDyedZsysKQgbClNZLycpky438iol33JRYn+FgMKoVCC7JDXpTZPuGz6EQ/fUksP4IdmUSVtDSLmBj8fJPtFPdff8b4zkWFxLsiSjaM2gyS7mMmo5NPsQv/w51b7gRJl/4wdxPxU97bXk=,iv:bhymbp/IgEKgWphoahY9ZCQFIstT5l/4Yz4OD6qhhXM=,tag:Sh+elUSTyIH7TRXWv1nPkQ==,type:str]
    pgp:
        - created_at: "2026-06-15T05:56:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdADztfVfTJ46QSiI4CfxD8KlbvHGgJIDtbksgdvJzfLCIw
            DQEA+zvKoegsisKFFHcGOGhDkno103iMG04XCRg1J44GUOLne0hhgbjCNRsXW/3f
            0lEBK0OP3mR+TE5r+3ONMlCPesRBTn9y2GyWU32FVPvAErZOHVwB6nx5LueHErCi
            XQknW3eUc+BmY4vPad8QWc99YADkZa2RfcS0eaNDSqgKWRI=
            =2e8h
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
