apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3
    namespace: miniflux
type: Opaque
stringData:
    cnpg-s3-id: ENC[AES256_GCM,data:7Et6xruSwbaT7X2yocFl+GqL1XJcQGs5ZQ==,iv:GNikczqiNWQhGCzW1eJBMPqftoOC7O3qJE+NGN6vxwM=,tag:PtpB8GiUlLRvFRViXhP1Cg==,type:str]
    cnpg-s3-key: ENC[AES256_GCM,data:SX0h3YFlPVoWRdBTOpR5GG9cyVLta+Jge1PhBY+3dA==,iv:ncb6hWIm/Fc3ng5Rq6Dc32039jhLxzGcy3p9NRfHZ/Y=,tag:R/1PsIewQ8w2Kh8Dt4VLOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQUIwd3daRE1Pa1ZFam1t
            SG5aeHI1Zit5cm1mamxTVndHZzd4WE9ZbGhNCkN6TWZkbkRnSnJ5Z215OHBBUUJS
            c2VvbG53ME0yK3NkWHJGUkxsQ1JCVHcKLS0tIHVYQnJ6SG50aG0vNkpsQ0ZRU0lt
            TDFNSENqV09BS2lKZ3JvN1RBTFFVM2cKbENBsI/1j38yFBb98fhV43dGHdo+9JqZ
            vo1bBLW14QjQLgLz/n8vQ3xMplvTQMWwIYJePgeVtoGQCekhnC7nxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T06:54:29Z"
    mac: ENC[AES256_GCM,data:5qHIa/kW7hLBKcHyDcZ74rf1RI4tLjZDRLLuUXB3PCHfJtDOVqzpAz1JUnUZVAkziU0+nob2d6Vj1KQMxbWDXZfG38dPu4JyooAtsEzkXVc5fELqfjEFYUPWSWD3Nrq5bjBLMI6+lAGM1vnx27cNh8p/ojNpTc8gNeg0zkcWK0w=,iv:uPrZIZSRl/Ooy3SF+0elz1fA4ORW7Awhix8luf4b6qE=,tag:ijYKJ/6Pe+PuFHMmW8XwzQ==,type:str]
    pgp:
        - created_at: "2026-06-15T05:56:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdADztfVfTJ46QSiI4CfxD8KlbvHGgJIDtbksgdvJzfLCIw
            DQEA+zvKoegsisKFFHcGOGhDkno103iMG04XCRg1J44GUOLne0hhgbjCNRsXW/3f
            0lEBK0OP3mR+TE5r+3ONMlCPesRBTn9y2GyWU32FVPvAErZOHVwB6nx5LueHErCi
            XQknW3eUc+BmY4vPad8QWc99YADkZa2RfcS0eaNDSqgKWRI=
            =2e8h
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
