apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: miniflux
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:h5myCG/uDQhpbYoTmwRUcKNtg7cvtqSvlOHR4fy0tPA24IJSSDAkmbqm8yOg19C+KCBldc7cgqz9F4GkVH+Z3RKXvJvr1B1dtn3NmH2tzve0S8QUL7iu7iWEzC/N0hHDcyfjlCBuTEYIthaOKLxuHbYIUn7DJ+fT9BbRLdMgRqjG8kTvb+KjkFwDf9NyaYjxYIDj+obISIEj/QqRk18hS647sUQOu3SHPOp478OjV0+WfR5UWv5tMTNX3vmUw6EHSmh63NV03Bcykl2TdB+1WueaVmjpm/GfH29l69BIgDSPoGDHA6paxEE0QQwP4qO5SiKmJ7Wc44nVjOaq9u5WGQb/fFFt+zJpZpXCmRA7vSmZvhPHdMY1ZnZ4tUVaof8GousgpcJTu1KZ,iv:IX4FKsHwKYORHQMsCYmMNvr6r+7VzwiN7+8Y5AWCJoQ=,tag:URegH/aCuyz4VUSoctj12A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPR0VzbSsxTmZCWTc0cDNK
            YXA2d1VreEZsdStITmFhb2MzNkcyZ1hOUWdRCmNGNlczUjVOQkZHNms3d01PaDJO
            blNyUlVlbVpzS1RoYVczYjNQYUZBMXMKLS0tIHJ3ekNZS2J1a2lzY0FTTExxd3Aw
            R2VZQ3BET25TZEFSdk4yVWgxV2dza28KjufcTjTmEWh717dNZbhY1O9giyx2TXyP
            NFO1tHAj4fAVZej3vvOzZbg575OwFMMNSTizFHGT8YWAYuDzeUlU3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g2c7cf39cnfrhjdsrcpjz8zsm9gtwymwnjum78x870xa40vtdgys2ddwls
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T05:13:39Z"
    mac: ENC[AES256_GCM,data:Q9DRnuLL4KFQSzRkbS6Dq4N4ttfoVLGD912VOeWsoz2YBTHkdSx+JjdCjyR+JlFVTQwrrsia+Li3ljbPKdVXu2iE7ZqMRVBQnAmPVF/brnHvgybaPLdpXJPKiSJQIrtHKDf2rQ/H9DxFJC12Bjmz3SPWPE8XCjSqnNag5owpy6w=,iv:ppiVCl+7ykHgX7xfTW9DI5Hhhc7/zmO/n3XoeRB5gjY=,tag:kuoB7/5PPvEnmJZaWnQr7A==,type:str]
    pgp:
        - created_at: "2026-06-11T05:13:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAsEQFblI0j7qBUSklYgn1MHz5IocSdEwPrp4bfW+wtA8w
            QZdRfa/98W41Hdc/ex9rXMP9E3BWEm4zSk/CI+kHbgPEAGXO+yFVuqM7m4r/7xOJ
            0lEBv0vRGTyPKCBBcvCnFkoUyed0GqaylmET2w1nBzOoVnv8LZr5StTcGlBnyaV8
            oW9SaRHU9SzvollY4IouxyEQzu6JTzet3pgFr17frHo6DF0=
            =JiwD
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.0
