apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: miniflux
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:h5myCG/uDQhpbYoTmwRUcKNtg7cvtqSvlOHR4fy0tPA24IJSSDAkmbqm8yOg19C+KCBldc7cgqz9F4GkVH+Z3RKXvJvr1B1dtn3NmH2tzve0S8QUL7iu7iWEzC/N0hHDcyfjlCBuTEYIthaOKLxuHbYIUn7DJ+fT9BbRLdMgRqjG8kTvb+KjkFwDf9NyaYjxYIDj+obISIEj/QqRk18hS647sUQOu3SHPOp478OjV0+WfR5UWv5tMTNX3vmUw6EHSmh63NV03Bcykl2TdB+1WueaVmjpm/GfH29l69BIgDSPoGDHA6paxEE0QQwP4qO5SiKmJ7Wc44nVjOaq9u5WGQb/fFFt+zJpZpXCmRA7vSmZvhPHdMY1ZnZ4tUVaof8GousgpcJTu1KZ,iv:IX4FKsHwKYORHQMsCYmMNvr6r+7VzwiN7+8Y5AWCJoQ=,tag:URegH/aCuyz4VUSoctj12A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMczVnVVJCZGhoRHRuU2hI
            OGMvVG1VTW5mckNNUGNrZDdOeGdZV05ZU3o0CjIvQVI1YVVoQnFQaHlIVGtqK2xt
            WmVDdEVBQVlLVHU5bFZFamliTWlsYzAKLS0tIC9kSzRGNnc2NUR1ZGdhRXRUV2lG
            MnZabG9pa1lvQWptV2VwVlowb1AzUEEKlxINWToBqkDdsy/O46pduY0PI9KhjmeP
            kkflb8SfDcFYYOivnSwhyf6wh503QC7nJi58fMip5+2YZ8sZ5x3ozQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T05:13:39Z"
    mac: ENC[AES256_GCM,data:Q9DRnuLL4KFQSzRkbS6Dq4N4ttfoVLGD912VOeWsoz2YBTHkdSx+JjdCjyR+JlFVTQwrrsia+Li3ljbPKdVXu2iE7ZqMRVBQnAmPVF/brnHvgybaPLdpXJPKiSJQIrtHKDf2rQ/H9DxFJC12Bjmz3SPWPE8XCjSqnNag5owpy6w=,iv:ppiVCl+7ykHgX7xfTW9DI5Hhhc7/zmO/n3XoeRB5gjY=,tag:kuoB7/5PPvEnmJZaWnQr7A==,type:str]
    pgp:
        - created_at: "2026-06-14T17:46:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAAgc6ki7WfV/nCtXsQwg4r9hDnooL+XcHKXWvMP6YjEMw
            aXq/sOfwlOCeFqRj88ql2euW4ZBwxBYpTawMUp+HCI6ZIuevVG3nIU0VE5UH7HqC
            0lEBpT5k4qIDeSstpUByUVKJ0KsYOfuIIBCNJ0cfBr0WPyMYTIx5/+5qtliUNj2q
            RNkjsqoemCldy/MK3cmhjxf6z/XR1AHd7X8UawC/FBXGOuk=
            =y/Ab
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.0
