apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: miniflux
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:LbWrqAH/6Pmj8rdLgUgGpOu6uLFrd4iJkpsS6ozLTv6XVy0yXsGvlhmKeWZJG6M8oG/lslWPQ7DMMTWOxeYp5Pord113kShG0JduArCwex304htUikssVpfAxsvwu2w8n+6FfqqHNINY/8Y064g6bPhV6CdGaS0z1jF90O7mhbB4MEfdDwyUEqUo/aoWtV8c4lPmUkk=,iv:bCxRvqTQ0/lS0LxyCWPRrN1FCVSAzFBpd2smfYSPDEs=,tag:SIkyB9Q836nlxuFcrkpvxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM2k4dHIzeFliamgwYmNo
            bERhZ3ZnT3ZRMFYrM3NRQ2hVcTFCa2RJNGxjClVmZFdZMFdyU0dySnppdlNseFp0
            V21CVjNhV1pjQnNxai9HSldldmRta28KLS0tIE5VRFRFNlFOa3Nvb1ZFMm1QSHo0
            UFRmWjViVFF2bmRIeG5VVjRtM29ZSFEKIZQ8tgg61coOSNHfjjcgRwr2KIUb9umQ
            pXF/qfXH0RKcmSZZI01K+LOtBS4W5vWhTIgeDgssUIXT2lXfX1BeXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T08:54:49Z"
    mac: ENC[AES256_GCM,data:k3idX1r/TNkOubt0mZr0K290Bsv1uKxPCGkTv3vYB8llFwqJuZgCsUeuDElH/fSZuFKe5oJ/MmFyV01AbmKtzpOMMNR++U1WPlH2Gb/+T9nxklQE/rBsk4lva6rrMw5PIziFbh8XMBH5Z8txjgwBGR959cl0k1werWM7RdALVvE=,iv:aez3525sf0mqFJ4AAqAB1Te9OQc/9rtnvQt7oltnMjo=,tag:ImPvs/AgDrOQiDK3vbWb5w==,type:str]
    pgp:
        - created_at: "2026-06-15T08:54:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA81VfoKKHJUCCFJZC5tiJ0hUQ11F4pvy8HABXc0aZ6UQw
            oWmXfX6CSgeltghkTlZGiOdgYRuay3uHVy0pi1P3Zqh5/uiAVhfBJjGK7HEEkkOg
            0lEBg42EhSYpe5/dWTbM9F/HlrDpD6KtmBbrXiAXuA5+9ixkaWai/LpsDrqinb6W
            Arr/h/coBrLkv0aRRHM9fgoDCNxGE49p6p7Q7k0TLA3W83Y=
            =P/xF
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
