apiVersion: v1
kind: Secret
metadata:
    name: telegram-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tt5Fa5PX6pRjjbiiv6GmAcq82tv/f3iKFI+VF+pRLTrYNYRCPE3a3DMMFXbASQ==,iv:w9cOpx5ybFDpxuxY6emN3rUk3C8TK3yaOIPFtIsI0cA=,tag:3jVDujRRDPbLXpYewcwlag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZjRwTVFLQjRCcEpzTGNm
            eUtuRFNBYVNDSEZPbS81VklsZjUrVlZoRUYwCkxEa2hiRFd2MWdVY212d2hrd0Ey
            enhqZ0QzcGFsN0VkOWhTTFY2QzBlYm8KLS0tIExpT0VTeGVVRjZBa1JPekIvWWxr
            U2xUSzBOVml0Q1BNaUlDQ1VnVHpvRmsKyA6I/C6EVEd8U+qeDpf7cZxmXCStLUo2
            5eXBaqWmQt3w8EJLPnQKKBIeAGzdcPKpOzm7m98qJNqTXbFO4uZ5RQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g2c7cf39cnfrhjdsrcpjz8zsm9gtwymwnjum78x870xa40vtdgys2ddwls
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T09:29:04Z"
    mac: ENC[AES256_GCM,data:o1XQWKYooSP+SkTeIPlFe83xX3U9lGPIpvciJD1UrEDnum6BGcUPflUgtvKmk7UopFmfm4fppFdhn+oghGCkgq3G+gqaxIS2lPEc1UQum/Lh8wuBvrgxpqp1bLyyfsgIdkEQ6QsEIMKR6r8evahCT76i4LOzFmpiyjTG1NMBR1c=,iv:dDNvrYK7PQZN2QytVDn1oShBAynx2nssa4BtMs8LDR4=,tag:rjgnkRrXdDSnNkbz0Dpzdw==,type:str]
    pgp:
        - created_at: "2026-06-11T09:22:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAcxGyPERd/wj/Bo1R7pnRod4Mp5oMmlcntcG3GRcn1Tww
            JXk+Wp1i+IoNrlKhHsKjVYP/tiZN/xNhVwr2EZyCSw8YkSra0GviBOidqvO479vM
            0lEBbslr1zbaKXyplj0kgBvrfnoJSdJXPjJTElbmQrUPSrlGiiQ1gx2RlYct3LyU
            7bbzHUx5bfLLAClbEIz3C8rowp2pnkQ+y3sL1S724MTU3yU=
            =Gkq2
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.0
