apiVersion: v1
kind: Secret
metadata:
    name: telegram-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tt5Fa5PX6pRjjbiiv6GmAcq82tv/f3iKFI+VF+pRLTrYNYRCPE3a3DMMFXbASQ==,iv:w9cOpx5ybFDpxuxY6emN3rUk3C8TK3yaOIPFtIsI0cA=,tag:3jVDujRRDPbLXpYewcwlag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVEpFMDNKZVZuQWFaOUdw
            OFlqT1lHZWhsdWtjditrY052ME8vWUY1UFJBCmtEeUs2eUIxaFlVblRISUNiVDZW
            czF5bGdEZjBCQlRpdFAwMGVtUXJPc2MKLS0tIFJjYWF3SjBteGlTOE1DeHVXWVlP
            aHRoNEo4SFFML004ZFVmQStKWEpncDAKlgNAbcZzVEsPATsFl6ZdEIpFA/tAw547
            uQJBqMrFVS9VbNzYEm3V4v3LJrBh21KmbNTZjDMBhucKuTlqVRh8Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T09:29:04Z"
    mac: ENC[AES256_GCM,data:o1XQWKYooSP+SkTeIPlFe83xX3U9lGPIpvciJD1UrEDnum6BGcUPflUgtvKmk7UopFmfm4fppFdhn+oghGCkgq3G+gqaxIS2lPEc1UQum/Lh8wuBvrgxpqp1bLyyfsgIdkEQ6QsEIMKR6r8evahCT76i4LOzFmpiyjTG1NMBR1c=,iv:dDNvrYK7PQZN2QytVDn1oShBAynx2nssa4BtMs8LDR4=,tag:rjgnkRrXdDSnNkbz0Dpzdw==,type:str]
    pgp:
        - created_at: "2026-06-14T17:46:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAVvMOQh6afwx9I1q+SKBg1eSrlM6soH3/xmE+JJQMEGcw
            aoM/YWPVtgzX33/VfX9swrCwoQkpOsOLBH5tTVhEAeo4KNEMXPes3JOss0RNhGZ2
            0lEBsU7zbzjeGZN29hwfIEjLbIvQiAE4jdaP7apB6Qa+3WUd/GQKs8hlSOIWlCN9
            PDX4nma6jqwpq6Rn2ekXUyBRj2WiFfmA9F5XIyT0d3a0XYc=
            =rI31
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.0
