apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
    labels:
        reconcile.fluxcd.io/watch: Enabled
stringData:
    token: ENC[AES256_GCM,data:oCpSEsIPRIMR2Py8wXGqL91UD4BeGFfeS4UfqGFx9OTg6f+p5N3Rnidqi+Hyp+2k8O0mArstJKb5F0EJ+ipGpA==,iv:CH99K6NAI+SlX9/JeWtt2+7Bm0pzlb718UryrLXJqHE=,tag:/t7s1tA43J2JHuO0D/lX+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcGExN3FleHFySklVempo
            WFJNVzErQmNqeklyczdMOHpDUTVZNXVYN1RvCjQ4REpUTkJPVnZaU3RDMmhHVTE5
            R3B0Qi9HUVVMN0t2dmRtR25xQ2V5YncKLS0tIEoyVHF4cU1tdVJXU3k0QU5kNEp2
            VlRNT1l5MXlLendVbmcybk0xTUVZOFUKmDrW/H/4/GmJinSoquvjbjfoB8IMZ+De
            Qv0yfFj0w0C053L0ds7aqliB1pc8VFsCiSdSplcvjV+VhEKmjG0rVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T10:50:23Z"
    mac: ENC[AES256_GCM,data:5ZqaZZeYNqLRqcxCKVaBIXwCh1lyBgwTmgT5p+XBVEeo9CayonXOzJXIUJMpeq0RIpn0NTbRLPLYRFijA1TgvB9XZSd//yq2yFRzVWmXINB9qeR4ApPvuqFc8d/YfzumRnm+2iiqy2Zj+0F5EhIRl2UPKVces11PoiGRAc24bzI=,iv:jOal2cOg7I7ze2o650ITIvTPht7F5F334rn50pR+W4Y=,tag:vHP++oHErapoSB57v1A1jA==,type:str]
    pgp:
        - created_at: "2026-06-16T10:50:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAyTQs9nNaJa9JP68QsAKu8+71+Iw8rVi6yT5n4mlF60Yw
            jBIGodwO6roUsJPC8GldUHNOh1VfCdBhAJWg5XTEu8NlzIHZK/xlPFiE+1ML/cli
            0lEBahsHAoMzsmlYe1ko8pr75MW6HFn9EbUPivI/+jbYFr23yYQ59tbHVj4JUlFr
            8lWsYaUPovyIp0ur+9rOkqjm29snzuQM9qs/lLaSLyISPwQ=
            =7DYM
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
