apiVersion: v1
kind: Secret
metadata:
    name: juicefs-secret-oracle
    namespace: kube-system
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:HixiECurhd8dQKmWtr8=,iv:S7s+j5p2PSOgMThKk9RtETWe5asm9oeqyBzvpH4NLco=,tag:CHJR+44Yha8pQBJyoxJ4+w==,type:str]
    metaurl: ENC[AES256_GCM,data:tcw+i+JKNhRgTCEVH/wvsALeZo6GTjBoV8U2zxCZnr0REZp752cOeJODKlYwr40LL3815eb/UGEi+l/y8ra8ISwHi70hMchZ,iv:LQ423FRNmfFahVsORirJhRQ3I+ic4RsIv+SO+RyIxRo=,tag:z8KisRExTCv4r1yO3enfUQ==,type:str]
    storage: ENC[AES256_GCM,data:VDM=,iv:rKfRb45Ojgq8+s+XPjtMfLGzMyqr6d0xGEGtkhDqYjE=,tag:i+lJjQPNZJE8nYiI+lqcwA==,type:str]
    bucket: ENC[AES256_GCM,data:6wFjj76v9csx+vqcCflutZm1KMPQ8TiigUS8E8tQ6sX/okZLcskmuhyvZhGQyEFvndkTyTs5mzy9,iv:rhJZbXWKcSKRQe4VaisPf7mNhqjo5lRgtQRgkJ03fbw=,tag:WQPdPH8Kvaie5Ybh/GL+6Q==,type:str]
    #ENC[AES256_GCM,data:4ppCjt3mH+ttFr9Ym39Y+hEdVM6bO5R8BihW+9CY87o=,iv:Mdl4MOGgL0onXxkh29zgbjC6E10GhBDHgHt1sMBeCHs=,tag:Uop5YToM13SdQw2GMsIZmA==,type:comment]
    access-key: ENC[AES256_GCM,data:2avwVedkyPSg1h4KP4WlsfNYbdypliB5eQ==,iv:40peZlSA4za3ktZ6U2tb9OssikUFtnW15Mgjp+XOKkA=,tag:l5UIwzrk49EAAz7ZovLUEA==,type:str]
    secret-key: ENC[AES256_GCM,data:eSK9qW65JY42FUB4IgDPa0mHstkpSTtJPsFjlTi5Eg==,iv:u+vtva+0IdFXUee6FOtjczEi7RsvP8ARKiV3aQqvtSs=,tag:nLwDpotI4LLmUowmM4qV+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS1JFSTFBRE1zcUN4MWF0
            eisvaTZtNFhwUHJndGUvVmhPbTFCZm1SajB3ClB6b1ZNeHBNamQ0OWdJeWdRUEVS
            ZHYxcGhjaXREYWk3WlhlWDNPa1B5M1EKLS0tIE9tVVMvSmZnTEsyS0xITXFEUDdQ
            YUhzWWVBZ2l4K3A0WGVXVGNINE5MUkkK7NO43P79XOTbynxn0MAaEYKxIH6/Z9Fj
            oOI3/HZ2YWfIghnkLEcMJUpDzn7zPrjYoGgpHFOSJ0+wWHiMWsUqFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T06:58:07Z"
    mac: ENC[AES256_GCM,data:/uiVWMh+dIcCqm+armTLWsvihQu1wITLtbOaLJBxL7hCNLwrF3Pvdg6pJ0qF1uBDvqn626QBN1B8QztvU8bppoPxwNec6mdc6qRCJEP5VumwJ0dMOBngulRAhX4BdsbpTZ1E4cp3jvYh6ji6bzDKBdTYMAPBL0upFYFLUJzmNkA=,iv:ZNvTYejsiB5mzsJNdyNoI4NosaAga4u1YYY/skRc508=,tag:DXGgUwS+v3v4G9D22C/QwA==,type:str]
    pgp:
        - created_at: "2026-06-15T10:36:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAYz6REeq57mTwu3vrApsr3LWXE548Rt5d0VIEKmeaRRAw
            1gpPoK3A1CpZq2P4gOrvDyj2hhEb66erp6jM40ebP5aZwpZ/FdsVX2oLpwaWUSU+
            0lEBJZ/Sc11aHUKDi4D8DicBPBCYM7OJi89KZdYFsEzjyDioh+8KODSFI6aWkE/R
            aEmEURtvITxJMWzaWBF83PSIiLCan+7MmSzuRqkgX+jr0k0=
            =kSro
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
