service:
  type: ClusterIP
  port: 1411

persistence:
  enabled: true
  storageClass: "juicefs-oracle"
  size: 1Gi

nodeSelector: {}

appUrl: "https://auth.rmtt.tech"

database:
  enabled: false
  secretName: pocket-id-db-app
  host: pocket-id-db-rw
  port: 5432
  name: pocket-id

env: []
