---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miniflux
  namespace: miniflux
spec:
  interval: 10m
  dependsOn:
    - name: cloudnative-pg
      namespace: operators
  valuesFrom:
    - kind: Secret
      name: helm-values
      valuesKey: values.yaml
  chart:
    spec:
      chart: ./charts/miniflux
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    database:
      size: 5Gi
      storageClassName: local-path
    nodeSelector:
      topology.kubernetes.io/region: oracle
    env: []
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
