apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: lldap
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:9bvEoRn2R9zERTstuTRNe7lte976efbwLXNPg5nw2WUVklzjMFkCTONQ7WFN4np1l+ohWeM8oWfgLWCcYJUxAonVaQ9h/vhM3T11OYgWNwppST11fqSC2+89Xri3OZq1LHM67FtJe7Ydtl6p/tWhYr3TzW2yKOOZbLydNHagJr20uj0GDbSXrByGVya/N2KYpNLz75sP3LuLeSte2c6orSKVaTgtmjEC36yz0Ro0dRPLw/d55huDqg9G7QsTAhaTqGxGJCYJhRLvo1ITkvpRKuBXTnVpmVmyRJlxzl5rfPjZGMVHnO6gZkawWiyVTLDDK4W4blRzz3iyk83SzuylhBly4HJmEe5iAAB3qhqdVT9qjaQT6O+zKZ4kSCG6b+qfT0ngdGDOCdYG4TzWBZoF4t3V0lFtsWtSGWh+97xxvgM/8+iNmolNuoz16wuPCpxdhdNb+4u7eMhNB6QMY8Q6m6nOSY8EY1Hhg0Tfqf93njKCsJ/sdmxCEgyE/dpooLNJzE3x15A6ZniVPZKM5KZDpN0yZ+RCwLHjBW+rMC46UwqcC18BCK3lbCoK4EDja9VgsMimxUOMUC5hujPmSh4O7GpWvs2antlWZEcmVda/d0hW/WXk5nhlL4P8,iv:kGfeI+g8daFgWzzFxPYVU/1G59oZfj9rfmdwLoOae30=,tag:uUWS8H4xiHloLq1FyTVG8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcjRmd1RGaDNPTHRXc1FT
            NGpwckVRSDhzY3JaR1dTdWRxQWlkamhrY3pZCjVaNkk5bUFDQjh2YVBSTjlNWTFw
            alBOOWVCRjkvNFdlR0ZnRWVYcmpMZTgKLS0tIDFEb3BvWjZIMElMN21obURza0lS
            RTMrRlgwWkEvMk54Q3NjcEp4dkJrTTQKFPvJxfzoS0wLH9ICNAr1Ao+8rKTmqNKx
            rHkgEX1/oT1q8fwuaPhIcdjWA3q9NhVIcsqsZNO515jqq0uav2aCtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T12:23:57Z"
    mac: ENC[AES256_GCM,data:HVUhw1g5mA4tDr/+DeQOZTNd0+KqMGCfvZ68kAohGDfY4CNhW0Un9mNgNfCVaYTTmTAHDSjW0Hs8KLErNbOsBkYJx5kBCQBgw1/WTP0Hz4TiMIBDuG56nwIsPXUTD8RBuCf/ZGdBZJmuNrjEplHEXjeLExoWk52uxn7GvG1GxGQ=,iv:xTKOBuCFP23ryv3k/vo46QyQY4cSACLDqD0MKTuuktg=,tag:gy+rFU4Qhi7RXLY3Bm5uSg==,type:str]
    pgp:
        - created_at: "2026-07-03T12:16:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAng3au+LBZ5C7kU8iIlYWW0BjRoyKv3Hd7OWnz/lbtEcw
            NbMXtmfuo9fkspyyYAJmVmzKATUgREsjG8fwEIdTHIACEf9icGHCcdYGRIGqTN3h
            0lEB28v2lNICg6erbgY7wol3M7ZgURXjQ7x3UbTmNL5RoxUMlfFejtPVdGso37kZ
            pcmF7E7xNTwOG/US43WLG478DFAsaVrR6pKhlp+6azvS4sA=
            =I+to
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
