apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3
    namespace: authelia
type: Opaque
stringData:
    cnpg-s3-id: ENC[AES256_GCM,data:GkYICZrGfnmncjsNg31FGUmLpxWqD9+B7Q==,iv:T38YySgKcz/qA5nonRcneSrvh5X5ZK4mZ7icM8ClVVY=,tag:6uBcv+j3hMNoHshwWVvYxg==,type:str]
    cnpg-s3-key: ENC[AES256_GCM,data:emi/RsHrV1lLE0k9E/f9UE0qaEqDNb9ghnAeQkMJ6A==,iv:eiLAEDvjKooLWwHb7n/31VfWmsGfKIyyNUizxePKwNw=,tag:jFcPU40U3I4uv4ZszFIhYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT2JWNzcrQW5WKzdtaHl2
            Sy85THdoWG1ROVZJanZyVjVKc2h5ekNIS2k0CkhQbkNrcityNFcxTGNqZGxoZnNq
            SzdHZEpIRHNBVTREcDlKUjAzV0RlNW8KLS0tIDkzMDkrVTJydTBYZFJ6MFo5VVZE
            TnRWckplQUFJZFRxR2pTNUhPOHQ4UVEK2kLS5U9Can13CGlL44qXBXSqFci+GRp+
            wk801X65Odr8xVRXbe/RqD+sraoanHmBEAyA7VK8IeClk8ywZgdjHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T06:54:07Z"
    mac: ENC[AES256_GCM,data:CsbufprmMB4LHjbTI542h5Kc+bFzRmBnXcMf9Nd0AVosGLC0DX0pJ0vTQNM/EpMOOfYkaVHIE/TPaMdYAgTmhg+GGKijSJs8nzhYaEae49IQFRfNreDntvzy0OYlWXAIZoNQJVvKzTV3+ovje4W/IfqHDcrij8a5OwPa41EOILo=,iv:38vS4IQPtNNbG5p5dfL7Nc+KzvzXoZAgasvp7wlIwWU=,tag:y6/TZ6rQwauqurInbxsi1A==,type:str]
    pgp:
        - created_at: "2026-06-15T07:35:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAOTI1EhgzTGb2+D9YoKvk6/NO7SSMrXQY8foyeKCbknAw
            xzm+rZwS1LSBXqGZe+dA7anlBWs4fclPnnl7rdeIJ9MIv9FVAiVISXkd7/qnmbks
            0lEBsgul/rDxuzZ8gNLIKUgy1r8EMYrGJU1BgxXKZ/heqO1SGEm/kykM54GL3kny
            et1d7c+zw79esAUGi0UWGXgh2ZNQR1Ag47caiLPvf2acgis=
            =ICs3
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
