{{- if .Values.persistence.karakeep.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.karakeep.size | quote }}
  {{- if .Values.persistence.karakeep.storageClass }}
  storageClassName: {{ .Values.persistence.karakeep.storageClass | quote }}
  {{- end }}
{{- end }}
