{{- if .Values.persistence.karakeep.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-pvc
  {{- with .Values.persistence.karakeep.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.karakeep.size | quote }}
  {{- if .Values.persistence.karakeep.storageClass }}
  storageClassName: {{ .Values.persistence.karakeep.storageClass | quote }}
  {{- end }}
{{- end }}
