{{- if .Values.persistence.meilisearch.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.meilisearch.size | quote }}
  {{- if .Values.persistence.meilisearch.storageClass }}
  storageClassName: {{ .Values.persistence.meilisearch.storageClass | quote }}
  {{- end }}
{{- end }}
