apiVersion: v1
kind: Secret
metadata:
  name: karakeep-env
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.secrets.nextauth | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  OPENAI_BASE_URL: {{ .Values.secrets.openaiBaseUrl | quote }}
  INFERENCE_TEXT_MODEL: {{ .Values.secrets.inferenceTextModel | quote }}
  INFERENCE_IMAGE_MODEL: {{ .Values.secrets.inferenceImageModel | quote }}
  EMBEDDING_TEXT_MODEL: {{ .Values.secrets.embeddingTextModel | quote }}
  OAUTH_WELLKNOWN_URL: {{ .Values.secrets.oauthWellknownUrl | quote }}
  OAUTH_CLIENT_ID: {{ .Values.secrets.oauthClientId | quote }}
  OAUTH_CLIENT_SECRET: {{ .Values.secrets.oauthClientSecret | quote }}
  OAUTH_PROVIDER_NAME: {{ .Values.secrets.oauthProviderName | quote }}
