apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-db
  namespace: miniflux
spec:
  instances: 1
  storage:
    storageClass: local-path
    size: 5Gi
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
  affinity:
    nodeSelector:
      kubernetes.io/hostname: oracle
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://postgresql-backup/miniflux-db
      endpointURL: http://nas.infra.rmtt.host:30188
      s3Credentials:
        accessKeyId:
          name: cnpg-s3
          key: cnpg-s3-id
        secretAccessKey:
          name: cnpg-s3
          key: cnpg-s3-key
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: miniflux-db-backup
  namespace: miniflux
spec:
  schedule: "0 0 */2 * * *"
  backupOwnerReference: self
  cluster:
    name: miniflux-db
