---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miniflux
  namespace: miniflux
spec:
  interval: 1m
  dependsOn:
    - name: cloudnative-pg
      namespace: operators
    - name: authelia
      namespace: authelia
  valuesFrom:
    - kind: Secret
      name: helm-values
      valuesKey: values.yaml
  chart:
    spec:
      chart: ./charts/miniflux
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    service:
      nodePort: 30004
    database:
      size: 5Gi
      storageClassName: local-path
    nodeSelector:
      kubernetes.io/hostname: oracle
    env: []
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
