apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3
    namespace: pocket-id
type: Opaque
stringData:
    cnpg-s3-id: ENC[AES256_GCM,data:AiwuW8cgsAYb0lygxcBp5aQeGtCXiz/HwA==,iv:2/cgDQb9T+QfVbxluh2x0MJUC0mc/TBjkhAMeOhJ3B8=,tag:rW7EUoQ3iIsyDzmnBHnYZw==,type:str]
    cnpg-s3-key: ENC[AES256_GCM,data:CN/z5bzY/l2vvGg6ucF5lL1LgnrTFnnpHNfBDvzRyw==,iv:mpiw6ambQjoHWl5nFb1+eAYvVpBDV1+dXd8sInpnQpE=,tag:Mj8+iNeletYsIh39XOFndQ==,type:str]
    region: ENC[AES256_GCM,data:PQJ4eOMhZMi5N10=,iv:hwgY34du+kV+CI+ot/9JMcquugAEYT0gLcZxqDLOO14=,tag:ZB+6DLFZ3ctDPPLkb6ZLVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdXV5YWFLSHMyLzgraGgy
            UHFnVmh5T3pyU2Z6aGQ0dFlaN040M0E2NVNzClVLN2sxZ1JFditPaVBhb0pnc2lx
            VHZTNURyVzFQS3hIU0VSaWdTUm1UTTAKLS0tIHZnc01LMDcrUGtPMlJ4TUloWEo4
            ZVFRWVRXZFJnZ1VaREMrYnVYQ0F0YWsKLEipJA5lQN4phusYtRHlCH7cQ4vB4I6g
            Wr+L99+hKOYG/srXhVbgutQAx0wgz6eFPaQI98PBvQ9xGCfqESU13w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T02:49:00Z"
    mac: ENC[AES256_GCM,data:nu9fiBclw5Fw27uttUXgYT8+xZxA/EpQPYzHyWaBR+/MeQvsTwFBZTSm7x4LjrpWPy5UXjAMAz35r4Ugpk3mBDDoOiRyVPwgwe6vIkSJBL5TzxDY+ByWtqq1fhOCwB7a5Pmhv5mzBJAyuTIojfnVfZhlhpjLgdUKxxFiTpTrV3w=,iv:wcsA1zTGxrqBxQ/hvbY4aEv3FB1QwLPGtSpfzZPiZA0=,tag:qj0B83FUtPP7o9FsgOVYvA==,type:str]
    pgp:
        - created_at: "2026-07-15T02:49:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAxBC9hBYixAWM4bde2LcH1nzzdSaiQTNFUA2GZ7AUYHUw
            6dy4zgScjcHmrR1NMDgX4NvBjKNIpnv4msGbj14/SSS1NoPiDxSu63iBlzd/oxWQ
            0lEBw+KwKNLPibUz+l/U0fqPzcvrE2C/mlXgC6eoxP+8+7+6nNAlMZ+TDtdEq6RG
            emI5UXEx1nbSzKIzpG9W17wRSUSR64oFHplCOxjDUocjFoE=
            =YT0i
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
