apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: pocket-id
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:M8PAg+a7ObR6gsOB7+n23Xdaf6lnMHKgsaEZgdvmmVDJ+QKNi502P7vJjlu7yOLzEqgEUzKipt2inZjmv5YstgrqV3tyzBfRS8RxUXDJsgcJMLkFA6PAYWnF+g3lCJGL4jmrfRzNMm99LRxS,iv:LJJrpr9ujs9mJ7lt/hYcuWyrjaDIOLX5LUdm4PNrsJA=,tag:0LG7ADIQpM83/5g631jFgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3REVVRTZ4M1pDYmIyY0V4
            S2w2UHRpTWY2RjF0MGNiUTVyZXA1d1JjVzBjCnNzZ1lwNUx6MVNIeWpTTTdZNkUw
            aFpJeGdPRXkvWWVMbVNjT1ZuYnNKelkKLS0tIG05S2Z3NUJZSDhoc2FUazFad29B
            c3FsMUV6SjVaWkRyVGpzbVFBRXNyK3MK7VZGTOHZ2+yUt9LHky6t/q6MwLbQ+7xT
            BTYcoIEGtGAdvXfCj1fCQP2XapCEg1K54oVZOBXHUSX5zzlrFeF+Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T16:23:36Z"
    mac: ENC[AES256_GCM,data:JR+prHdp3k17NMzbpD905iVIim7mPJZuw6j5ZzDofBO+V/sNYDyDJ6NARQipa977ZSHZ6qfsKy5+btL/KUGaJBrF+YS07vpz3i1wPM15wHYN0In4zpHss+pH06UNi4UHpi6GciAYODeOJQOQRBJu7ijfpt08LbfJN9EoIOLQvfI=,iv:TfiTlVXxcQcrm6p5rP38LVz8Qz3HVWGSSCJWx2KmPCY=,tag:U8/UUUxlxf7sF1NFhq17uw==,type:str]
    pgp:
        - created_at: "2026-07-04T16:18:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAArpnnDLFQco0Aa6lOpNLYwm+sL+U6DEDjTRAJMngukIw
            4V6A5XZyRi5QdEV6kKR/MCr5lU26kVGa1/aM+P/4sY15JA+aO0FnA0DbVexP/MCp
            0lEBFXLYxEDGGpYdtU0Metsryg4k6Gve4VWWG9BTcrJyyRIF/fW1qnkGLYmc2uNj
            ++ff55GimY4fKk0XIiEeF0aVTH0NTIj4hlzF81qi7knMucc=
            =JO4Y
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
