apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: pocket-id
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Me3NL/LP7tGX3LwOCJCxqwSzVUPpzmLGfQS49+QyBC4a6xiXhMrShQkgZ1ziI1UtX75KXo/b5CKB4oWcLatkR52svmoS+oSnEhVxUq111yZfVOerI3IIcVPZO/ggkIN0RAP9VH8MA7P2BlXRcr/mPt+t5cyGLCD8Txmze/BG91+FeHsqBkivckF1yMJPNn7bP8x8xgUJPaZ7RcPoS83YGY1F07Nn9TpCsy8X2FzBLq0qpByF5heOqz+T,iv:XEau8hv4Z4QG7gwxgayIczpT5/bKcA+N7qqJ60khpx8=,tag:UOykrBRRyTPDWZt64QENhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3REVVRTZ4M1pDYmIyY0V4
            S2w2UHRpTWY2RjF0MGNiUTVyZXA1d1JjVzBjCnNzZ1lwNUx6MVNIeWpTTTdZNkUw
            aFpJeGdPRXkvWWVMbVNjT1ZuYnNKelkKLS0tIG05S2Z3NUJZSDhoc2FUazFad29B
            c3FsMUV6SjVaWkRyVGpzbVFBRXNyK3MK7VZGTOHZ2+yUt9LHky6t/q6MwLbQ+7xT
            BTYcoIEGtGAdvXfCj1fCQP2XapCEg1K54oVZOBXHUSX5zzlrFeF+Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T16:43:29Z"
    mac: ENC[AES256_GCM,data:YhQ0psmOki1nhXNyaeIKgoKcj+kBF9TSQAkqwmyxvb/9KUCHXQgW+wlscqJbh1IzRrneYI3v/gF/1gK1W8bz4RckPe5NG1BBCNGChld7rfTl/VA6P4E4K2DfwncxblSFvUimdmHHGt0XlpohBsOiEpJfnlwqjpc+nXZvFOSO4sc=,iv:Dt+1OwYjvj31pZxccryfZbr1tTPF/a2w5NE1aF0M1X0=,tag:vxlajfYSMwowy8m4icwg/A==,type:str]
    pgp:
        - created_at: "2026-07-04T16:18:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAArpnnDLFQco0Aa6lOpNLYwm+sL+U6DEDjTRAJMngukIw
            4V6A5XZyRi5QdEV6kKR/MCr5lU26kVGa1/aM+P/4sY15JA+aO0FnA0DbVexP/MCp
            0lEBFXLYxEDGGpYdtU0Metsryg4k6Gve4VWWG9BTcrJyyRIF/fW1qnkGLYmc2uNj
            ++ff55GimY4fKk0XIiEeF0aVTH0NTIj4hlzF81qi7knMucc=
            =JO4Y
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
