apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-db
  annotations:
    "helm.sh/resource-policy": keep
spec:
  instances: 1
  storage:
    storageClass: {{ .Values.database.storageClassName | quote }}
    size: {{ .Values.database.size | quote }}
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
  {{- if .Values.nodeSelector }}
  affinity:
    nodeSelector:
      {{- toYaml .Values.nodeSelector | nindent 6 }}
  {{- end }}
