apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  labels:
    app: miniflux
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: miniflux
          image: "miniflux/miniflux:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: LISTEN_ADDR
              value: "0.0.0.0:8080"
            - name: BASE_URL
              value: "https://miniflux.rmtt.tech"
            - name: CREATE_ADMIN
              value: "1"
            - name: RUN_MIGRATIONS
              value: "1"
            {{- if .Values.secrets.oidcClientSecret }}
            - name: OAUTH2_PROVIDER
              value: "oidc"
            - name: OAUTH2_CLIENT_ID
              value: "miniflux"
            - name: OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: miniflux-secrets
                  key: oidc-client-secret
            - name: OAUTH2_OIDC_DISCOVERY_ENDPOINT
              value: "https://auth.rmtt.tech"
            - name: OAUTH2_OIDC_PROVIDER_NAME
              value: "Authelia"
            - name: OAUTH2_REDIRECT_URL
              value: "https://miniflux.rmtt.tech/oauth2/oidc/callback"
            - name: OAUTH2_USER_CREATION
              value: "1"
            {{- end }}

            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: miniflux-secrets
                  key: admin-username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniflux-secrets
                  key: admin-password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: miniflux-db-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniflux-db-app
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@miniflux-db-rw:5432/miniflux?sslmode=disable"
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
