apiVersion: v1
kind: Secret
metadata:
  name: miniflux-secrets
type: Opaque
data:
  admin-username: {{ .Values.secrets.adminUsername | b64enc | quote }}
  admin-password: {{ .Values.secrets.adminPassword | b64enc | quote }}
  {{- if .Values.secrets.oidcClientSecret }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | b64enc | quote }}
  oidc-client-id: {{ default "miniflux" .Values.secrets.oidcClientId | b64enc | quote }}
  {{- end }}

