apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3
    namespace: affine
type: Opaque
stringData:
    cnpg-s3-id: ENC[AES256_GCM,data:p0wPIGJWtgE8egUH7XzJW/SuqkN5O23xSw==,iv:21d+xnkwj05YNdi8R5u2MR54yyAQOBn1LNsQYp44OJE=,tag:o9lLA9ELIXJnzhm+u6aaJg==,type:str]
    cnpg-s3-key: ENC[AES256_GCM,data:COTbi+RlGXN/SbFEyAb8OFkzCGnGr/jyur1D8m2P/w==,iv:JmVk5BP5ZNj0WySpnzWCuWNzgzVIABG3QHsAj3WXU1Q=,tag:nYWPoiBBnOJ5inUm80DxPA==,type:str]
    region: ENC[AES256_GCM,data:FjohWnQ9mQhVqpI=,iv:ppD/ifok+o4Z0HXhyOq+2Mt322RuyEG6ZhVL9EX48bY=,tag:ryJ0l57tjFF07poCvcacSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWG9xMHhxV0lVY3ZLV1pu
            Ky9XcDR5OXYzaU5pL25LYUZ2dzQwcG5vanpVCnZ6dWpFeFRQUVNla2FCcjY4UFI0
            Mklzb3VvWlgxNWtxc2pxMjRWQXl1M3cKLS0tIDR1eW1Gd09zTnE4YlNHMTBJYlY4
            UHZBN3RCK09PQTFVSlI5dTRhdUVxbWsKcih76L+j+vgA81FxzYjXTrfCOq9LdWDh
            WPD8/NVsVzCIzyZX8eyosSFbV/6u1Km5uB6+hubW6anI5urV0UI4pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T09:49:38Z"
    mac: ENC[AES256_GCM,data:QUMRb6p8CHlihOMFdZEbhZX/zZl58xSNoYlWIVBNbLXfVW1JRCgqC4vrvCux9DkETd9ZEAOH+GLF1emAvcmb04/wLhnezWWHgDx3oOif16Pv030ltrFUBqDocUsXYE+75JKVkgYwT2CI5BSDtFKh/FKnwgaDnnEwkN74ZY0mftc=,iv:QIx8ttDGzOzEKGI5lphEWT4Zgn2Dd3sb54UN7fw2u+g=,tag:H3t88tCTv88AlVGEO7d6qg==,type:str]
    pgp:
        - created_at: "2026-07-10T09:49:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAEaxlInzXh4eYSkP//eEybI18QhteSVD2/PD3W4rkoyEw
            0vMQ+NH+YKTuUrE0H3z7/lmz3LUnNXhFXiIPeVjjKOFhnzkwdjbFJ0PVeJjQqpm2
            0lEBbGZN5QGlZSeSMXt13p7NI9CZLElvGtLCFdZYge5fBzE9/YIKMN/mCcvczf85
            P0uZ9/VaQewNAqQiXaY9w7Uiv76BOHsI29D3Ul/txJ5s+hk=
            =E2dA
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
