apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: affine
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:f8T0bQsI6qQ=,iv:dCJrAZD6sJM2+9cLKD1gTuQuUcNNY5Pc0CksPZYgZAo=,tag:ELgvxoGQhIP9QXb4eN16QA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeG9BRG1BMkFzNUFuRTYy
            U2JQS1BxNCtESzdjSXFNcy8wMVZONHBOYWtJCk1Rbyt3VUdOTnVFc1lORERQY2NM
            N1E5R0wyb2hadnFqZmdaeG1xd3dJWlkKLS0tIGh3WndkVWZRK0tBSTlVWE1iajZK
            VWs5a2grYlNENXUxaHpHTVFwUUtGUkkKl15qmSDD0bVDgMDGN6OBWVeElTaAlvZG
            OS3ymmDbfJLjXn+2aj3AsLtVQixFsGBnMUElldo4fzAQl4bHtPTdEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T10:41:40Z"
    mac: ENC[AES256_GCM,data:tZAWDJ8GzDcz5WOt4iIEShs5YJvRKIh8zdkCjtdoVyt2pucC+5tpU7YlkdSt2uMypesF3gUfDPP2EE3u+ydclIITWvvMzhNTBXJDLXniqBYz8uM2r8kH+bmAwvOPPSblaP48Qmu/E4myM3bMKjo/0qZ8Ws9HTX5dExEzJ4XOwI8=,iv:RBeTByWbTzBtrOWPCk2UbNVqbqFQ8szCaX38ZvIlV+I=,tag:V0sk32pag57ssEwVsi81bg==,type:str]
    pgp:
        - created_at: "2026-07-10T10:41:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAiizJISbbAuqDGK0+9yzsUdlMlht0EvaJJu13A41T8Q0w
            oSOe9C72Y7L+eChp/NJG1ERxsrhYJ3Hl/62cpLxX2CvNh1dK6fWTxramVtXlkrd8
            0lEBrbUVJa9OBmQ7vVRMRS4JdQ5o3Po39oCe95jDnw75ihfXytPYY/77EulD4nlF
            BOKovYTMk4P0g0Fshz9P3SP0mcC8Ur28feWBTBlkP4duxpA=
            =HiZd
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
