apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3
    namespace: authelia
type: Opaque
stringData:
    region: ENC[AES256_GCM,data:T8x0GxiT,iv:GSAJpji2zQcJMnIFujBmwTg+1kuqyONPI6J4jkBdCH4=,tag:Ot0RbY1hBqBZFuwwneXZzw==,type:str]
    cnpg-s3-id: ENC[AES256_GCM,data:d8FNg/IuIkeEu8B8WpxO0HFxiF54w3OS29Q=,iv:XcbNzL5zn7CGV6ioQxiC0xf1492nOU69NQrxa1/C1Sk=,tag:oh8dUw7/6FO6X9N4ONIfAg==,type:str]
    cnpg-s3-key: ENC[AES256_GCM,data:dhLuAvWbbWSicv5qaJXWtcX9/2iC6/qMj3Cqq+GlYEvs90IdbyPMTZBWPHCwj0HU0sPcsdcKlIfFLg5NjQ3gvg==,iv:QUkyUQVX3KslMifThfmcfwNawCAeMcJhhXxBjhtHv8g=,tag:NfSMVUYhpg+3sJo6qRy0jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT2JWNzcrQW5WKzdtaHl2
            Sy85THdoWG1ROVZJanZyVjVKc2h5ekNIS2k0CkhQbkNrcityNFcxTGNqZGxoZnNq
            SzdHZEpIRHNBVTREcDlKUjAzV0RlNW8KLS0tIDkzMDkrVTJydTBYZFJ6MFo5VVZE
            TnRWckplQUFJZFRxR2pTNUhPOHQ4UVEK2kLS5U9Can13CGlL44qXBXSqFci+GRp+
            wk801X65Odr8xVRXbe/RqD+sraoanHmBEAyA7VK8IeClk8ywZgdjHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T01:51:19Z"
    mac: ENC[AES256_GCM,data:5oCfvJudkUe79W8s5X5h3v93qbPkl2x7ZasPHsvJ6N2NBUAsFVM5aooQ8ajacp8jOHtzl4110gwJGakksJdt6GOuwnmW2Q5hrTPRrUMGO1OsAWWB+DQRPse3d0OB2vheRiRSp9GBH8oKUtWIJfUUHin4f6AunpxI4zy95865gHc=,iv:4dkYRPAkX9Bb6pw0QvBMx4Oyd2iZlAp7SPfDrgaXgjw=,tag:fKXaWsT3IAwPWrUaShHa8A==,type:str]
    pgp:
        - created_at: "2026-06-15T07:35:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAOTI1EhgzTGb2+D9YoKvk6/NO7SSMrXQY8foyeKCbknAw
            xzm+rZwS1LSBXqGZe+dA7anlBWs4fclPnnl7rdeIJ9MIv9FVAiVISXkd7/qnmbks
            0lEBsgul/rDxuzZ8gNLIKUgy1r8EMYrGJU1BgxXKZ/heqO1SGEm/kykM54GL3kny
            et1d7c+zw79esAUGi0UWGXgh2ZNQR1Ag47caiLPvf2acgis=
            =ICs3
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
