apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3
    namespace: authelia
type: Opaque
stringData:
    region: ENC[AES256_GCM,data:T8x0GxiT,iv:GSAJpji2zQcJMnIFujBmwTg+1kuqyONPI6J4jkBdCH4=,tag:Ot0RbY1hBqBZFuwwneXZzw==,type:str]
    cnpg-s3-id: ENC[AES256_GCM,data:QqAHEueqFd0JPWk1DicYQlJVf52sC+HAlf4=,iv:yv8FBo/8wc1L4bt71VeuVvca6TDmngeKnTTihyVGrIU=,tag:ptugJR9RQX8YrZt3A5/7Kw==,type:str]
    cnpg-s3-key: ENC[AES256_GCM,data:EVatgMawovQZnIREL3Go306EmQWyKJlBL5JCjnjPGHs0yNC0a58QYFXmOXG4jULOfulFVNOs9siWd/CNy7lL,iv:vvsB5tpEY1wljmACm7CdhuIbCsW7SgsP6i0TghbkmTs=,tag:9nU9wXzQ/jFoQwt+lhcU8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT2JWNzcrQW5WKzdtaHl2
            Sy85THdoWG1ROVZJanZyVjVKc2h5ekNIS2k0CkhQbkNrcityNFcxTGNqZGxoZnNq
            SzdHZEpIRHNBVTREcDlKUjAzV0RlNW8KLS0tIDkzMDkrVTJydTBYZFJ6MFo5VVZE
            TnRWckplQUFJZFRxR2pTNUhPOHQ4UVEK2kLS5U9Can13CGlL44qXBXSqFci+GRp+
            wk801X65Odr8xVRXbe/RqD+sraoanHmBEAyA7VK8IeClk8ywZgdjHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T12:16:10Z"
    mac: ENC[AES256_GCM,data:of53KFY7ktqNM7PfQEzgWr2F19CPj+YKMilhPtMRGsHCXK0Q6+kRVFYSknveqHz4nvgHZHvPYOlKg9IVCYBWfgPqsd8wr0VUqIpzo4lc5465xZtq2SVyFR2ObxBP2P+5Gx0RRnD2Du2I/J3Pj+8Y+2/dnSG5S4mw77htKhtjdfs=,iv:e+dKiTHZWNcX5VI39R8PV2X5Bwlv6TVh1prsQF8n5Ls=,tag:YfOJ43eoc1v7SeCneZ5mGw==,type:str]
    pgp:
        - created_at: "2026-06-15T07:35:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdAOTI1EhgzTGb2+D9YoKvk6/NO7SSMrXQY8foyeKCbknAw
            xzm+rZwS1LSBXqGZe+dA7anlBWs4fclPnnl7rdeIJ9MIv9FVAiVISXkd7/qnmbks
            0lEBsgul/rDxuzZ8gNLIKUgy1r8EMYrGJU1BgxXKZ/heqO1SGEm/kykM54GL3kny
            et1d7c+zw79esAUGi0UWGXgh2ZNQR1Ag47caiLPvf2acgis=
            =ICs3
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
