apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: karakeep
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:jN7eEY3ruBwCJQY9EK0d4ZzRMPi+Kg2eWDNdkmvdrmwvzFHpjiEpq8LlX/06xmxKx4zaQUb/KBaJvJRq/fgFZvb5OapUV/XXchZz07+hHHVpKHWHFvFbUc6fDKq+pdzTonrHs9wklkLTPZhp1ztPrpCUDxgWMGa/OyTRdXS248F8slGfFd4/aKKIR2hOoji37VjhsyS5QEkPMNV2QrmjZPqOiPdCYj9kP5scf2r/g9CGHQZHJ1cx6kAzc2ysxDAfgaZcuqiKqt16x/n97Yx/hmiWsJhslVjGHlmT8/dS1lyZ5k3ce8Wglw4PB1vbCYaOm/SaROpISB20XVUtsyvHCFflu44DqCrpZyhysdHa0Vfs7LkjpReoZeCvh+h7sOJ3MuVWoCkTIEwybJpsbTxjdOXKqQczXHijAvFdkqIw9ITWNN12jV8sOue0ZUZf5cT6BX99C9Q4L2mX56zl3SSQ8iXkhazMJnKzviHmfPLt8Zyd2J1Oydat+f0/SVp85ZS9UwEwNxLjUV+aoNT3jV1Tmomx1TWF7xxfyOL1sMgX4xFc0Tr1zJTXAwMm6kx+HVbbV0h4le23wB5iZ0N4d2oP8xqZbMEVswae3+EkIRRxGKIh9mXbAyYkuCwjIegAsD9pmO7uAzfv8h0aNcPwtpftDh7YE3AunEpn,iv:eAtVw5uGerR/jo0BFHxU1sZqXeXxol68HBKy6qmGeDM=,tag:MjKRhrAfEdwL5eciaVSN3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMTV6Vmh6Q05kTnRtV2FP
            cnBuSklaTm1WblpwNFhGTEkvUkhwTE9IZlVnClp1N2xoNmo4V2dxZkZvQ05pQ0Vr
            QStrOU5sUDBFMHVtVUNPNlNEWVRwM0kKLS0tIGwrNWhtbTI4c1pCaEttbDIwcXdE
            YVlKekYrajZ0SDVPTEF1RnVSSnFBU0kKs8CfIodIkWuFMS4bVtK6+loRRyKoDh+5
            ynIAiEFTGl3bsIjjo7+qw7fLGX+FwV2QMqOL6x1Xs+857iHbPDs+hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T12:28:08Z"
    mac: ENC[AES256_GCM,data:HhT1KcUySEkIcV2aOJ34Aw1SnZXlhC5MgV/2tH2KbqOrEAQND/SzvGM7qWvzr/cderZuneyRQZROkKG/WR1Ba37fDN/KU5CG6NC1p3rlMtM49wgNcYeRytnE9Dzraoo+YSkz0ZWPKg/Lnawiqlsz+tdytw3m4C+6D2tHOBR8rQA=,iv:5PBSoTDD4/m/7E4JYlPwGEcIEuLwAFuO2xgmWnwK0D4=,tag:swayESQTGkvenMee3I9NVA==,type:str]
    pgp:
        - created_at: "2026-06-14T17:46:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA4w2YNyo4oB3m9sZlFSJor4uz7SPT5FVVAVTAwHAbNAsw
            mkKtrnvOjl8iEWu8WfcBQWzK0kTT2YUVdBY4lwjjOaNKNM7XEzEq4jqlG7MII4HD
            0lEBykkI1EEs8/wVLUo43OkoYJk4IJmFD3CsTDXLYKEq3hROzg1d/nXddPdHxMgH
            vd9/IgOqqlXpDGZ83t4JCwj2dbojoCl+LdwGIiyUXXf98Co=
            =8poF
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
