---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trilium
  namespace: trilium
spec:
  interval: 10m
  chart:
    spec:
      chart: ./charts/trilium
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    nodeSelector:
      topology.kubernetes.io/region: oracle
    persistence:
      enabled: true
      storageClass: "juicefs-oracle"
      size: 100Gi
      annotations:
        helm.sh/resource-policy: keep
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
