apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../secrets/flux-system
  - ../../secrets/kube-system

  - ../base/flux-system
  - ../base/kube-system
  - ../base/operators

  - juicefs-csi-instance.yaml
  - storageclass.yaml
