---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-oracle
provisioner: csi.juicefs.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - writeback
  - cache-size=102400
  - cache-dir=/var/lib/rancher/k3s/data/jfscache
  - free-space-ratio=0.1
  - io-retries=5
  - noatime
parameters:
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret-oracle
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret-oracle
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  pathPattern: "${.pvc.namespace}-${.pvc.name}"
