---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: operators
  interval: 10m

  valuesFrom:
    - kind: Secret
      name: helm-values
  chart:
    spec:
      chart: ./charts/authelia
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    config:
      domain: rmtt.tech
      autheliaUrl: https://auth.rmtt.tech
    nodeSelector:
      topology.kubernetes.io/region: oracle
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: local-path
      annotations:
        helm.sh/resource-policy: keep
  upgrade:
    force: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
