apiVersion: apps/v1
kind: Deployment
metadata:
  name: alist
  labels:
    app: alist
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alist
  template:
    metadata:
      labels:
        app: alist
      annotations:
        checksum/config: {{ .Values | toYaml | sha256sum }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: alist
          image: "xhofe/alist:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 5244
              protocol: TCP
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: UMASK
              value: "022"
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            {{- if .Values.persistence.main.enabled }}
            - name: main
              mountPath: /opt/alist/data
            {{- end }}
            {{- if .Values.persistence.userData.enabled }}
            - name: user-data
              mountPath: /opt/alist/data/user-data
            {{- end }}
      volumes:
        - name: main
          {{- if .Values.persistence.main.enabled }}
          persistentVolumeClaim:
            claimName: alist-main-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.persistence.userData.enabled }}
        - name: user-data
          persistentVolumeClaim:
            claimName: alist-user-data-pvc
        {{- end }}
