{{- if and .Values.persistence.enabled .Values.persistence.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alist-db-pvc
  {{- with .Values.persistence.db.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.db.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.db.size | quote }}
{{- end }}
