apiVersion: v1
kind: Secret
metadata:
    name: helm-values
    namespace: kube-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:KsytFXNFhRx7tT3+DEKiBMMsQZXosDggy6RLrve6vpSqF8WtestD9OY0GOucICDPZQbjWBilz+ZT3rxVuZo7vS2M0kVaiF37Vl4a6Wj8TJs5e/difpdzRnQXlGqYp28lNVVC1QdD/Bt7pKkQUHYOjqIoqgR8ZHnWUE7VsXgE2TsrmAPrvdWoE5mBn/R8pZd7dD8NK8OxRuD6UZ9Qi3zIxN9Tq2aS6N7cROvZeNnK6x/FhvAOxxKYiy4YYgYaE8W5OXa/t8iRrogLcI7z7QDMB8p51I1LtqVQiTL9nseQhGURFSNQlO9+XqOoKhZ4D/LEvo6kGAF9Nzm2etcAMcAnJFuH6sBkvyBwv09lyidY1Ki0EQ4ow9MsTUGkSPjqsMZAEKOAumKQQmoUn3FbL4yKQu5KMdGicnJ8Y2YrqG79VqBfD0R78I4uxj6s7KugAgwGYT4rRNOIXVl0XjnseHCiaKSzrjgxTDpUyKeOfbMNTloCBdvyZ/+y+btGGCku6CLq5EocEmZZL/GKeZYpvFb6AKGM460UINl7aS1dZtHSSDA4pYHVqiMtJwx1N9ztw8Bx4THY+47c2kc2IS4hcMLN4t+udOzG+r0yvbx6UTEq+BBqul4h2/b+SwHdmIf7Q1BUuHuJh6miOHzwCscuAOfV24LEBUH/wvIjRoomn6+KqqO8cvHZnyKAiqOpxpRZ+akbbOtrITEK9q22jnvH/vbdjtQ6lfNYR5Dk77EB2jFne0Ul8xyCXkHVSX2Ojo/aNsQdTwQOd3/dN+izG1vXIiDzxYQKJYo6PxgVi1AHCz1t54ihPKhPwNGuJU0odCyTdELw6mvnNctYkLhn+PlYX3chmyo+pDSPcx10q/uygweTza0KbIZpKkchxcZ8gPw653V9yfsKETwAc5MHaVkHcdCED04N,iv:n0xsi42Exhgv4G7jqB6dDNXdYtvrNaeBGo7nRqSAyRQ=,tag:mGdETHtDn1PGv4NBi+x/ZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU2Z3UE16djJGeHFGanFY
            RjZhR3pyWWcyays5Zzcybjd0aFMzaEJiSlhVCmFWVTY2SVVueWtsWUNGY1cwSWtE
            TjFWaTFtMlZ6eTdHR2hGdG4zM0ovdkkKLS0tIGxQSGYweW95bURldWNvY2lsSzR2
            YURKY0xSRFFpUktKbTUvVnpsZDhzNmsKV4C9E4FcsZOIl1Ze669Iw+z8r31KYQ7q
            NvD/KYjAmvpi5VILKr1UrI57daJ+dQGrKJjJUJb1GrwC4r+La+qRxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n2zrgjhj3kgwtthmf56ryv84ygqk6tpymt4heq4x2d2ckrcfsdwsc3spqd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T14:20:24Z"
    mac: ENC[AES256_GCM,data:EzKi3LS8mze73png6XVnNWZWWfKOw7u4YDahu2Ip4rLusP6gtWhRUU7OMVi5EvHaKcnGFY0ligrCqv/S/zc7Ugxe10iFlrKiv1FbrPOk7mqc1LEGZMhrN1Fn1nYU2vMH62KhpkFnK13zX5Z7wifOs9Q44W9d69rXJIo/Z+6WdH0=,iv:HaeJoyXbyrLsKDHRh4R2WflcGljWQiKqk0GYHp7OMl8=,tag:l/KEIsguZd42variZJUcbA==,type:str]
    pgp:
        - created_at: "2026-06-18T14:10:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wV4D36+3H3ly1I0SAQdA64kuAKG6kD2JJrErdbJZQKmE++SYZ7Dz+jK9J3udzSUw
            ZegXiyIGNmOTq7V7uSKQJBkzEmhcsOsJcZww2CnfpZeLI9SHdQp0jUB0kzBspG6D
            0lEBGp7+Vkoh8NmITb59Fe7/f1GqEfTWuEdD5cAlQoKQ0hiCgbKscDJxTd4Q2zuU
            kG3Og7p3qbBsa13aHWC+06nA6TrgBLQRbti9h7TpCmrvaCE=
            =ercM
            -----END PGP MESSAGE-----
          fp: BD15904159AF89DEB3A61039DFAFB71F7972D48D
    version: 3.13.1
